// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: ai.proto

package aipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WelcomeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TodayContext  string                 `protobuf:"bytes,3,opt,name=today_context,json=todayContext,proto3" json:"today_context,omitempty"` // short free-text summary of due items etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeMessageRequest) Reset() {
	*x = WelcomeMessageRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessageRequest) ProtoMessage() {}

func (x *WelcomeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessageRequest.ProtoReflect.Descriptor instead.
func (*WelcomeMessageRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *WelcomeMessageRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *WelcomeMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WelcomeMessageRequest) GetTodayContext() string {
	if x != nil {
		return x.TodayContext
	}
	return ""
}

type WelcomeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeMessageResponse) Reset() {
	*x = WelcomeMessageResponse{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessageResponse) ProtoMessage() {}

func (x *WelcomeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessageResponse.ProtoReflect.Descriptor instead.
func (*WelcomeMessageResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomeMessageResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GradeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`                          // earned points
	MaxPoints     float64                `protobuf:"fixed64,3,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"` // max points
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`                        // weighting (sum should be ~1.0 across course)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeEntry) Reset() {
	*x = GradeEntry{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeEntry) ProtoMessage() {}

func (x *GradeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeEntry.ProtoReflect.Descriptor instead.
func (*GradeEntry) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GradeEntry) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *GradeEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GradeEntry) GetMaxPoints() float64 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

func (x *GradeEntry) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type RemainingAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	MaxPoints     float64                `protobuf:"fixed64,2,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	DueAtUnix     int64                  `protobuf:"varint,4,opt,name=due_at_unix,json=dueAtUnix,proto3" json:"due_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemainingAssignment) Reset() {
	*x = RemainingAssignment{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemainingAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemainingAssignment) ProtoMessage() {}

func (x *RemainingAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemainingAssignment.ProtoReflect.Descriptor instead.
func (*RemainingAssignment) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *RemainingAssignment) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *RemainingAssignment) GetMaxPoints() float64 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

func (x *RemainingAssignment) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RemainingAssignment) GetDueAtUnix() int64 {
	if x != nil {
		return x.DueAtUnix
	}
	return 0
}

type GradeProjectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	TargetGrade   float64                `protobuf:"fixed64,4,opt,name=target_grade,json=targetGrade,proto3" json:"target_grade,omitempty"` // e.g. 0.9 for an A-
	Completed     []*GradeEntry          `protobuf:"bytes,5,rep,name=completed,proto3" json:"completed,omitempty"`
	Remaining     []*RemainingAssignment `protobuf:"bytes,6,rep,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeProjectionRequest) Reset() {
	*x = GradeProjectionRequest{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeProjectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeProjectionRequest) ProtoMessage() {}

func (x *GradeProjectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeProjectionRequest.ProtoReflect.Descriptor instead.
func (*GradeProjectionRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *GradeProjectionRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *GradeProjectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GradeProjectionRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GradeProjectionRequest) GetTargetGrade() float64 {
	if x != nil {
		return x.TargetGrade
	}
	return 0
}

func (x *GradeProjectionRequest) GetCompleted() []*GradeEntry {
	if x != nil {
		return x.Completed
	}
	return nil
}

func (x *GradeProjectionRequest) GetRemaining() []*RemainingAssignment {
	if x != nil {
		return x.Remaining
	}
	return nil
}

type PathToTargetEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId     string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	RequiredFraction float64                `protobuf:"fixed64,2,opt,name=required_fraction,json=requiredFraction,proto3" json:"required_fraction,omitempty"` // 0..1, clamped
	Feasible         bool                   `protobuf:"varint,3,opt,name=feasible,proto3" json:"feasible,omitempty"`                                          // true when required <= 1.0
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PathToTargetEntry) Reset() {
	*x = PathToTargetEntry{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathToTargetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathToTargetEntry) ProtoMessage() {}

func (x *PathToTargetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathToTargetEntry.ProtoReflect.Descriptor instead.
func (*PathToTargetEntry) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *PathToTargetEntry) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *PathToTargetEntry) GetRequiredFraction() float64 {
	if x != nil {
		return x.RequiredFraction
	}
	return 0
}

func (x *PathToTargetEntry) GetFeasible() bool {
	if x != nil {
		return x.Feasible
	}
	return false
}

type GradeProjectionResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CurrentGrade             float64                `protobuf:"fixed64,1,opt,name=current_grade,json=currentGrade,proto3" json:"current_grade,omitempty"`       // weighted so far
	ProjectedGrade           float64                `protobuf:"fixed64,2,opt,name=projected_grade,json=projectedGrade,proto3" json:"projected_grade,omitempty"` // assuming remaining = max
	RequiredAverageRemaining float64                `protobuf:"fixed64,3,opt,name=required_average_remaining,json=requiredAverageRemaining,proto3" json:"required_average_remaining,omitempty"`
	TargetFeasible           bool                   `protobuf:"varint,4,opt,name=target_feasible,json=targetFeasible,proto3" json:"target_feasible,omitempty"`
	Path                     []*PathToTargetEntry   `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GradeProjectionResponse) Reset() {
	*x = GradeProjectionResponse{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeProjectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeProjectionResponse) ProtoMessage() {}

func (x *GradeProjectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeProjectionResponse.ProtoReflect.Descriptor instead.
func (*GradeProjectionResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *GradeProjectionResponse) GetCurrentGrade() float64 {
	if x != nil {
		return x.CurrentGrade
	}
	return 0
}

func (x *GradeProjectionResponse) GetProjectedGrade() float64 {
	if x != nil {
		return x.ProjectedGrade
	}
	return 0
}

func (x *GradeProjectionResponse) GetRequiredAverageRemaining() float64 {
	if x != nil {
		return x.RequiredAverageRemaining
	}
	return 0
}

func (x *GradeProjectionResponse) GetTargetFeasible() bool {
	if x != nil {
		return x.TargetFeasible
	}
	return false
}

func (x *GradeProjectionResponse) GetPath() []*PathToTargetEntry {
	if x != nil {
		return x.Path
	}
	return nil
}

type AssignmentSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DueAtUnix      int64                  `protobuf:"varint,3,opt,name=due_at_unix,json=dueAtUnix,proto3" json:"due_at_unix,omitempty"`
	EstimatedHours int32                  `protobuf:"varint,4,opt,name=estimated_hours,json=estimatedHours,proto3" json:"estimated_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignmentSummary) Reset() {
	*x = AssignmentSummary{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentSummary) ProtoMessage() {}

func (x *AssignmentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentSummary.ProtoReflect.Descriptor instead.
func (*AssignmentSummary) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *AssignmentSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignmentSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AssignmentSummary) GetDueAtUnix() int64 {
	if x != nil {
		return x.DueAtUnix
	}
	return 0
}

func (x *AssignmentSummary) GetEstimatedHours() int32 {
	if x != nil {
		return x.EstimatedHours
	}
	return 0
}

type StudyPlanRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug     string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UniversityName string                 `protobuf:"bytes,3,opt,name=university_name,json=universityName,proto3" json:"university_name,omitempty"`
	TodayUnix      int64                  `protobuf:"varint,4,opt,name=today_unix,json=todayUnix,proto3" json:"today_unix,omitempty"`
	Assignments    []*AssignmentSummary   `protobuf:"bytes,5,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudyPlanRequest) Reset() {
	*x = StudyPlanRequest{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyPlanRequest) ProtoMessage() {}

func (x *StudyPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyPlanRequest.ProtoReflect.Descriptor instead.
func (*StudyPlanRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *StudyPlanRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *StudyPlanRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StudyPlanRequest) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *StudyPlanRequest) GetTodayUnix() int64 {
	if x != nil {
		return x.TodayUnix
	}
	return 0
}

func (x *StudyPlanRequest) GetAssignments() []*AssignmentSummary {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type StudyPlanTask struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Day             string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"` // e.g. "mon"
	DurationMinutes int32                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StudyPlanTask) Reset() {
	*x = StudyPlanTask{}
	mi := &file_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyPlanTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyPlanTask) ProtoMessage() {}

func (x *StudyPlanTask) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyPlanTask.ProtoReflect.Descriptor instead.
func (*StudyPlanTask) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{9}
}

func (x *StudyPlanTask) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *StudyPlanTask) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *StudyPlanTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type StudyPlanWeek struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Week          int32                  `protobuf:"varint,1,opt,name=week,proto3" json:"week,omitempty"` // 1..16
	Tasks         []*StudyPlanTask       `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyPlanWeek) Reset() {
	*x = StudyPlanWeek{}
	mi := &file_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyPlanWeek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyPlanWeek) ProtoMessage() {}

func (x *StudyPlanWeek) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyPlanWeek.ProtoReflect.Descriptor instead.
func (*StudyPlanWeek) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{10}
}

func (x *StudyPlanWeek) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *StudyPlanWeek) GetTasks() []*StudyPlanTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type StudyPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weeks         []*StudyPlanWeek       `protobuf:"bytes,1,rep,name=weeks,proto3" json:"weeks,omitempty"`
	ModelUsed     string                 `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	FromCache     bool                   `protobuf:"varint,3,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyPlanResponse) Reset() {
	*x = StudyPlanResponse{}
	mi := &file_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyPlanResponse) ProtoMessage() {}

func (x *StudyPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyPlanResponse.ProtoReflect.Descriptor instead.
func (*StudyPlanResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{11}
}

func (x *StudyPlanResponse) GetWeeks() []*StudyPlanWeek {
	if x != nil {
		return x.Weeks
	}
	return nil
}

func (x *StudyPlanResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *StudyPlanResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type CmdPaletteRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Route         string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdPaletteRoute) Reset() {
	*x = CmdPaletteRoute{}
	mi := &file_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdPaletteRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdPaletteRoute) ProtoMessage() {}

func (x *CmdPaletteRoute) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdPaletteRoute.ProtoReflect.Descriptor instead.
func (*CmdPaletteRoute) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{12}
}

func (x *CmdPaletteRoute) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CmdPaletteRoute) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *CmdPaletteRoute) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type CmdPaletteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	Courses       []string               `protobuf:"bytes,5,rep,name=courses,proto3" json:"courses,omitempty"`
	RouteCatalog  []*CmdPaletteRoute     `protobuf:"bytes,6,rep,name=route_catalog,json=routeCatalog,proto3" json:"route_catalog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdPaletteRequest) Reset() {
	*x = CmdPaletteRequest{}
	mi := &file_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdPaletteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdPaletteRequest) ProtoMessage() {}

func (x *CmdPaletteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdPaletteRequest.ProtoReflect.Descriptor instead.
func (*CmdPaletteRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{13}
}

func (x *CmdPaletteRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *CmdPaletteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CmdPaletteRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CmdPaletteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CmdPaletteRequest) GetCourses() []string {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *CmdPaletteRequest) GetRouteCatalog() []*CmdPaletteRoute {
	if x != nil {
		return x.RouteCatalog
	}
	return nil
}

type CmdPaletteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Route         string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdPaletteResult) Reset() {
	*x = CmdPaletteResult{}
	mi := &file_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdPaletteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdPaletteResult) ProtoMessage() {}

func (x *CmdPaletteResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdPaletteResult.ProtoReflect.Descriptor instead.
func (*CmdPaletteResult) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{14}
}

func (x *CmdPaletteResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CmdPaletteResult) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *CmdPaletteResult) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type CmdPaletteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CmdPaletteResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	FromCache     bool                   `protobuf:"varint,2,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdPaletteResponse) Reset() {
	*x = CmdPaletteResponse{}
	mi := &file_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdPaletteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdPaletteResponse) ProtoMessage() {}

func (x *CmdPaletteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdPaletteResponse.ProtoReflect.Descriptor instead.
func (*CmdPaletteResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{15}
}

func (x *CmdPaletteResponse) GetResults() []*CmdPaletteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CmdPaletteResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type RubricRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	MaxPoints     float64                `protobuf:"fixed64,3,opt,name=max_points,json=maxPoints,proto3" json:"max_points,omitempty"`
	Criteria      string                 `protobuf:"bytes,4,opt,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RubricRow) Reset() {
	*x = RubricRow{}
	mi := &file_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RubricRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RubricRow) ProtoMessage() {}

func (x *RubricRow) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RubricRow.ProtoReflect.Descriptor instead.
func (*RubricRow) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{16}
}

func (x *RubricRow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RubricRow) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RubricRow) GetMaxPoints() float64 {
	if x != nil {
		return x.MaxPoints
	}
	return 0
}

func (x *RubricRow) GetCriteria() string {
	if x != nil {
		return x.Criteria
	}
	return ""
}

type DraftFeedbackRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug     string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	SubmissionId   string                 `protobuf:"bytes,2,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	SubmissionText string                 `protobuf:"bytes,3,opt,name=submission_text,json=submissionText,proto3" json:"submission_text,omitempty"`
	Rubric         []*RubricRow           `protobuf:"bytes,4,rep,name=rubric,proto3" json:"rubric,omitempty"`
	FlagEnabled    bool                   `protobuf:"varint,5,opt,name=flag_enabled,json=flagEnabled,proto3" json:"flag_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DraftFeedbackRequest) Reset() {
	*x = DraftFeedbackRequest{}
	mi := &file_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftFeedbackRequest) ProtoMessage() {}

func (x *DraftFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftFeedbackRequest.ProtoReflect.Descriptor instead.
func (*DraftFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{17}
}

func (x *DraftFeedbackRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *DraftFeedbackRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *DraftFeedbackRequest) GetSubmissionText() string {
	if x != nil {
		return x.SubmissionText
	}
	return ""
}

func (x *DraftFeedbackRequest) GetRubric() []*RubricRow {
	if x != nil {
		return x.Rubric
	}
	return nil
}

func (x *DraftFeedbackRequest) GetFlagEnabled() bool {
	if x != nil {
		return x.FlagEnabled
	}
	return false
}

type RubricFeedback struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RubricId        string                 `protobuf:"bytes,1,opt,name=rubric_id,json=rubricId,proto3" json:"rubric_id,omitempty"`
	Feedback        string                 `protobuf:"bytes,2,opt,name=feedback,proto3" json:"feedback,omitempty"`
	SuggestedPoints float64                `protobuf:"fixed64,3,opt,name=suggested_points,json=suggestedPoints,proto3" json:"suggested_points,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RubricFeedback) Reset() {
	*x = RubricFeedback{}
	mi := &file_ai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RubricFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RubricFeedback) ProtoMessage() {}

func (x *RubricFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RubricFeedback.ProtoReflect.Descriptor instead.
func (*RubricFeedback) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{18}
}

func (x *RubricFeedback) GetRubricId() string {
	if x != nil {
		return x.RubricId
	}
	return ""
}

func (x *RubricFeedback) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *RubricFeedback) GetSuggestedPoints() float64 {
	if x != nil {
		return x.SuggestedPoints
	}
	return 0
}

type DraftFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*RubricFeedback      `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Overall       string                 `protobuf:"bytes,2,opt,name=overall,proto3" json:"overall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DraftFeedbackResponse) Reset() {
	*x = DraftFeedbackResponse{}
	mi := &file_ai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DraftFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DraftFeedbackResponse) ProtoMessage() {}

func (x *DraftFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DraftFeedbackResponse.ProtoReflect.Descriptor instead.
func (*DraftFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{19}
}

func (x *DraftFeedbackResponse) GetRows() []*RubricFeedback {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *DraftFeedbackResponse) GetOverall() string {
	if x != nil {
		return x.Overall
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\vslate.ai.v1\"v\n" +
	"\x15WelcomeMessageRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rtoday_context\x18\x03 \x01(\tR\ftodayContext\",\n" +
	"\x16WelcomeMessageResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"~\n" +
	"\n" +
	"GradeEntry\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1d\n" +
	"\n" +
	"max_points\x18\x03 \x01(\x01R\tmaxPoints\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\"\x91\x01\n" +
	"\x13RemainingAssignment\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x1d\n" +
	"\n" +
	"max_points\x18\x02 \x01(\x01R\tmaxPoints\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x1e\n" +
	"\vdue_at_unix\x18\x04 \x01(\x03R\tdueAtUnix\"\x89\x02\n" +
	"\x16GradeProjectionRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12!\n" +
	"\ftarget_grade\x18\x04 \x01(\x01R\vtargetGrade\x125\n" +
	"\tcompleted\x18\x05 \x03(\v2\x17.slate.ai.v1.GradeEntryR\tcompleted\x12>\n" +
	"\tremaining\x18\x06 \x03(\v2 .slate.ai.v1.RemainingAssignmentR\tremaining\"\x81\x01\n" +
	"\x11PathToTargetEntry\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12+\n" +
	"\x11required_fraction\x18\x02 \x01(\x01R\x10requiredFraction\x12\x1a\n" +
	"\bfeasible\x18\x03 \x01(\bR\bfeasible\"\x82\x02\n" +
	"\x17GradeProjectionResponse\x12#\n" +
	"\rcurrent_grade\x18\x01 \x01(\x01R\fcurrentGrade\x12'\n" +
	"\x0fprojected_grade\x18\x02 \x01(\x01R\x0eprojectedGrade\x12<\n" +
	"\x1arequired_average_remaining\x18\x03 \x01(\x01R\x18requiredAverageRemaining\x12'\n" +
	"\x0ftarget_feasible\x18\x04 \x01(\bR\x0etargetFeasible\x122\n" +
	"\x04path\x18\x05 \x03(\v2\x1e.slate.ai.v1.PathToTargetEntryR\x04path\"\x82\x01\n" +
	"\x11AssignmentSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\vdue_at_unix\x18\x03 \x01(\x03R\tdueAtUnix\x12'\n" +
	"\x0festimated_hours\x18\x04 \x01(\x05R\x0eestimatedHours\"\xd6\x01\n" +
	"\x10StudyPlanRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0funiversity_name\x18\x03 \x01(\tR\x0euniversityName\x12\x1d\n" +
	"\n" +
	"today_unix\x18\x04 \x01(\x03R\ttodayUnix\x12@\n" +
	"\vassignments\x18\x05 \x03(\v2\x1e.slate.ai.v1.AssignmentSummaryR\vassignments\"b\n" +
	"\rStudyPlanTask\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05R\x0fdurationMinutes\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"U\n" +
	"\rStudyPlanWeek\x12\x12\n" +
	"\x04week\x18\x01 \x01(\x05R\x04week\x120\n" +
	"\x05tasks\x18\x02 \x03(\v2\x1a.slate.ai.v1.StudyPlanTaskR\x05tasks\"\x83\x01\n" +
	"\x11StudyPlanResponse\x120\n" +
	"\x05weeks\x18\x01 \x03(\v2\x1a.slate.ai.v1.StudyPlanWeekR\x05weeks\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x03 \x01(\bR\tfromCache\"Q\n" +
	"\x0fCmdPaletteRoute\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05route\x18\x02 \x01(\tR\x05route\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\"\xd4\x01\n" +
	"\x11CmdPaletteRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x18\n" +
	"\acourses\x18\x05 \x03(\tR\acourses\x12A\n" +
	"\rroute_catalog\x18\x06 \x03(\v2\x1c.slate.ai.v1.CmdPaletteRouteR\frouteCatalog\"R\n" +
	"\x10CmdPaletteResult\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05route\x18\x02 \x01(\tR\x05route\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\"l\n" +
	"\x12CmdPaletteResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.slate.ai.v1.CmdPaletteResultR\aresults\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x02 \x01(\bR\tfromCache\"l\n" +
	"\tRubricRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"max_points\x18\x03 \x01(\x01R\tmaxPoints\x12\x1a\n" +
	"\bcriteria\x18\x04 \x01(\tR\bcriteria\"\xd8\x01\n" +
	"\x14DraftFeedbackRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12#\n" +
	"\rsubmission_id\x18\x02 \x01(\tR\fsubmissionId\x12'\n" +
	"\x0fsubmission_text\x18\x03 \x01(\tR\x0esubmissionText\x12.\n" +
	"\x06rubric\x18\x04 \x03(\v2\x16.slate.ai.v1.RubricRowR\x06rubric\x12!\n" +
	"\fflag_enabled\x18\x05 \x01(\bR\vflagEnabled\"t\n" +
	"\x0eRubricFeedback\x12\x1b\n" +
	"\trubric_id\x18\x01 \x01(\tR\brubricId\x12\x1a\n" +
	"\bfeedback\x18\x02 \x01(\tR\bfeedback\x12)\n" +
	"\x10suggested_points\x18\x03 \x01(\x01R\x0fsuggestedPoints\"b\n" +
	"\x15DraftFeedbackResponse\x12/\n" +
	"\x04rows\x18\x01 \x03(\v2\x1b.slate.ai.v1.RubricFeedbackR\x04rows\x12\x18\n" +
	"\aoverall\x18\x02 \x01(\tR\aoverall2\xd6\x03\n" +
	"\tAiService\x12\\\n" +
	"\x11GetWelcomeMessage\x12\".slate.ai.v1.WelcomeMessageRequest\x1a#.slate.ai.v1.WelcomeMessageResponse\x12_\n" +
	"\x12GetGradeProjection\x12#.slate.ai.v1.GradeProjectionRequest\x1a$.slate.ai.v1.GradeProjectionResponse\x12R\n" +
	"\x11GenerateStudyPlan\x12\x1d.slate.ai.v1.StudyPlanRequest\x1a\x1e.slate.ai.v1.StudyPlanResponse\x12[\n" +
	"\x18GetCommandPaletteResults\x12\x1e.slate.ai.v1.CmdPaletteRequest\x1a\x1f.slate.ai.v1.CmdPaletteResponse\x12Y\n" +
	"\x10GetDraftFeedback\x12!.slate.ai.v1.DraftFeedbackRequest\x1a\".slate.ai.v1.DraftFeedbackResponseB*Z(slate/services/ai-service/api/proto;aipbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_ai_proto_goTypes = []any{
	(*WelcomeMessageRequest)(nil),   // 0: slate.ai.v1.WelcomeMessageRequest
	(*WelcomeMessageResponse)(nil),  // 1: slate.ai.v1.WelcomeMessageResponse
	(*GradeEntry)(nil),              // 2: slate.ai.v1.GradeEntry
	(*RemainingAssignment)(nil),     // 3: slate.ai.v1.RemainingAssignment
	(*GradeProjectionRequest)(nil),  // 4: slate.ai.v1.GradeProjectionRequest
	(*PathToTargetEntry)(nil),       // 5: slate.ai.v1.PathToTargetEntry
	(*GradeProjectionResponse)(nil), // 6: slate.ai.v1.GradeProjectionResponse
	(*AssignmentSummary)(nil),       // 7: slate.ai.v1.AssignmentSummary
	(*StudyPlanRequest)(nil),        // 8: slate.ai.v1.StudyPlanRequest
	(*StudyPlanTask)(nil),           // 9: slate.ai.v1.StudyPlanTask
	(*StudyPlanWeek)(nil),           // 10: slate.ai.v1.StudyPlanWeek
	(*StudyPlanResponse)(nil),       // 11: slate.ai.v1.StudyPlanResponse
	(*CmdPaletteRoute)(nil),         // 12: slate.ai.v1.CmdPaletteRoute
	(*CmdPaletteRequest)(nil),       // 13: slate.ai.v1.CmdPaletteRequest
	(*CmdPaletteResult)(nil),        // 14: slate.ai.v1.CmdPaletteResult
	(*CmdPaletteResponse)(nil),      // 15: slate.ai.v1.CmdPaletteResponse
	(*RubricRow)(nil),               // 16: slate.ai.v1.RubricRow
	(*DraftFeedbackRequest)(nil),    // 17: slate.ai.v1.DraftFeedbackRequest
	(*RubricFeedback)(nil),          // 18: slate.ai.v1.RubricFeedback
	(*DraftFeedbackResponse)(nil),   // 19: slate.ai.v1.DraftFeedbackResponse
}
var file_ai_proto_depIdxs = []int32{
	2,  // 0: slate.ai.v1.GradeProjectionRequest.completed:type_name -> slate.ai.v1.GradeEntry
	3,  // 1: slate.ai.v1.GradeProjectionRequest.remaining:type_name -> slate.ai.v1.RemainingAssignment
	5,  // 2: slate.ai.v1.GradeProjectionResponse.path:type_name -> slate.ai.v1.PathToTargetEntry
	7,  // 3: slate.ai.v1.StudyPlanRequest.assignments:type_name -> slate.ai.v1.AssignmentSummary
	9,  // 4: slate.ai.v1.StudyPlanWeek.tasks:type_name -> slate.ai.v1.StudyPlanTask
	10, // 5: slate.ai.v1.StudyPlanResponse.weeks:type_name -> slate.ai.v1.StudyPlanWeek
	12, // 6: slate.ai.v1.CmdPaletteRequest.route_catalog:type_name -> slate.ai.v1.CmdPaletteRoute
	14, // 7: slate.ai.v1.CmdPaletteResponse.results:type_name -> slate.ai.v1.CmdPaletteResult
	16, // 8: slate.ai.v1.DraftFeedbackRequest.rubric:type_name -> slate.ai.v1.RubricRow
	18, // 9: slate.ai.v1.DraftFeedbackResponse.rows:type_name -> slate.ai.v1.RubricFeedback
	0,  // 10: slate.ai.v1.AiService.GetWelcomeMessage:input_type -> slate.ai.v1.WelcomeMessageRequest
	4,  // 11: slate.ai.v1.AiService.GetGradeProjection:input_type -> slate.ai.v1.GradeProjectionRequest
	8,  // 12: slate.ai.v1.AiService.GenerateStudyPlan:input_type -> slate.ai.v1.StudyPlanRequest
	13, // 13: slate.ai.v1.AiService.GetCommandPaletteResults:input_type -> slate.ai.v1.CmdPaletteRequest
	17, // 14: slate.ai.v1.AiService.GetDraftFeedback:input_type -> slate.ai.v1.DraftFeedbackRequest
	1,  // 15: slate.ai.v1.AiService.GetWelcomeMessage:output_type -> slate.ai.v1.WelcomeMessageResponse
	6,  // 16: slate.ai.v1.AiService.GetGradeProjection:output_type -> slate.ai.v1.GradeProjectionResponse
	11, // 17: slate.ai.v1.AiService.GenerateStudyPlan:output_type -> slate.ai.v1.StudyPlanResponse
	15, // 18: slate.ai.v1.AiService.GetCommandPaletteResults:output_type -> slate.ai.v1.CmdPaletteResponse
	19, // 19: slate.ai.v1.AiService.GetDraftFeedback:output_type -> slate.ai.v1.DraftFeedbackResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
