// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: ai.proto

package aipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiService_GetWelcomeMessage_FullMethodName        = "/slate.ai.v1.AiService/GetWelcomeMessage"
	AiService_GetGradeProjection_FullMethodName       = "/slate.ai.v1.AiService/GetGradeProjection"
	AiService_GenerateStudyPlan_FullMethodName        = "/slate.ai.v1.AiService/GenerateStudyPlan"
	AiService_GetCommandPaletteResults_FullMethodName = "/slate.ai.v1.AiService/GetCommandPaletteResults"
	AiService_GetDraftFeedback_FullMethodName         = "/slate.ai.v1.AiService/GetDraftFeedback"
)

// AiServiceClient is the client API for AiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AiService is the tenant-scoped AI capability surface described in W7.
// All RPCs are gated by the monthly token budget (W7.5).
type AiServiceClient interface {
	GetWelcomeMessage(ctx context.Context, in *WelcomeMessageRequest, opts ...grpc.CallOption) (*WelcomeMessageResponse, error)
	GetGradeProjection(ctx context.Context, in *GradeProjectionRequest, opts ...grpc.CallOption) (*GradeProjectionResponse, error)
	GenerateStudyPlan(ctx context.Context, in *StudyPlanRequest, opts ...grpc.CallOption) (*StudyPlanResponse, error)
	GetCommandPaletteResults(ctx context.Context, in *CmdPaletteRequest, opts ...grpc.CallOption) (*CmdPaletteResponse, error)
	GetDraftFeedback(ctx context.Context, in *DraftFeedbackRequest, opts ...grpc.CallOption) (*DraftFeedbackResponse, error)
}

type aiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiServiceClient(cc grpc.ClientConnInterface) AiServiceClient {
	return &aiServiceClient{cc}
}

func (c *aiServiceClient) GetWelcomeMessage(ctx context.Context, in *WelcomeMessageRequest, opts ...grpc.CallOption) (*WelcomeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WelcomeMessageResponse)
	err := c.cc.Invoke(ctx, AiService_GetWelcomeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) GetGradeProjection(ctx context.Context, in *GradeProjectionRequest, opts ...grpc.CallOption) (*GradeProjectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeProjectionResponse)
	err := c.cc.Invoke(ctx, AiService_GetGradeProjection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) GenerateStudyPlan(ctx context.Context, in *StudyPlanRequest, opts ...grpc.CallOption) (*StudyPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudyPlanResponse)
	err := c.cc.Invoke(ctx, AiService_GenerateStudyPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) GetCommandPaletteResults(ctx context.Context, in *CmdPaletteRequest, opts ...grpc.CallOption) (*CmdPaletteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CmdPaletteResponse)
	err := c.cc.Invoke(ctx, AiService_GetCommandPaletteResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) GetDraftFeedback(ctx context.Context, in *DraftFeedbackRequest, opts ...grpc.CallOption) (*DraftFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DraftFeedbackResponse)
	err := c.cc.Invoke(ctx, AiService_GetDraftFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServiceServer is the server API for AiService service.
// All implementations must embed UnimplementedAiServiceServer
// for forward compatibility.
//
// AiService is the tenant-scoped AI capability surface described in W7.
// All RPCs are gated by the monthly token budget (W7.5).
type AiServiceServer interface {
	GetWelcomeMessage(context.Context, *WelcomeMessageRequest) (*WelcomeMessageResponse, error)
	GetGradeProjection(context.Context, *GradeProjectionRequest) (*GradeProjectionResponse, error)
	GenerateStudyPlan(context.Context, *StudyPlanRequest) (*StudyPlanResponse, error)
	GetCommandPaletteResults(context.Context, *CmdPaletteRequest) (*CmdPaletteResponse, error)
	GetDraftFeedback(context.Context, *DraftFeedbackRequest) (*DraftFeedbackResponse, error)
	mustEmbedUnimplementedAiServiceServer()
}

// UnimplementedAiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServiceServer struct{}

func (UnimplementedAiServiceServer) GetWelcomeMessage(context.Context, *WelcomeMessageRequest) (*WelcomeMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWelcomeMessage not implemented")
}
func (UnimplementedAiServiceServer) GetGradeProjection(context.Context, *GradeProjectionRequest) (*GradeProjectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGradeProjection not implemented")
}
func (UnimplementedAiServiceServer) GenerateStudyPlan(context.Context, *StudyPlanRequest) (*StudyPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateStudyPlan not implemented")
}
func (UnimplementedAiServiceServer) GetCommandPaletteResults(context.Context, *CmdPaletteRequest) (*CmdPaletteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommandPaletteResults not implemented")
}
func (UnimplementedAiServiceServer) GetDraftFeedback(context.Context, *DraftFeedbackRequest) (*DraftFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDraftFeedback not implemented")
}
func (UnimplementedAiServiceServer) mustEmbedUnimplementedAiServiceServer() {}
func (UnimplementedAiServiceServer) testEmbeddedByValue()                   {}

// UnsafeAiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServiceServer will
// result in compilation errors.
type UnsafeAiServiceServer interface {
	mustEmbedUnimplementedAiServiceServer()
}

func RegisterAiServiceServer(s grpc.ServiceRegistrar, srv AiServiceServer) {
	// If the following call panics, it indicates UnimplementedAiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiService_ServiceDesc, srv)
}

func _AiService_GetWelcomeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WelcomeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GetWelcomeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GetWelcomeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GetWelcomeMessage(ctx, req.(*WelcomeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_GetGradeProjection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeProjectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GetGradeProjection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GetGradeProjection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GetGradeProjection(ctx, req.(*GradeProjectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_GenerateStudyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudyPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GenerateStudyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GenerateStudyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GenerateStudyPlan(ctx, req.(*StudyPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_GetCommandPaletteResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmdPaletteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GetCommandPaletteResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GetCommandPaletteResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GetCommandPaletteResults(ctx, req.(*CmdPaletteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_GetDraftFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DraftFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).GetDraftFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_GetDraftFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).GetDraftFeedback(ctx, req.(*DraftFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiService_ServiceDesc is the grpc.ServiceDesc for AiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slate.ai.v1.AiService",
	HandlerType: (*AiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWelcomeMessage",
			Handler:    _AiService_GetWelcomeMessage_Handler,
		},
		{
			MethodName: "GetGradeProjection",
			Handler:    _AiService_GetGradeProjection_Handler,
		},
		{
			MethodName: "GenerateStudyPlan",
			Handler:    _AiService_GenerateStudyPlan_Handler,
		},
		{
			MethodName: "GetCommandPaletteResults",
			Handler:    _AiService_GetCommandPaletteResults_Handler,
		},
		{
			MethodName: "GetDraftFeedback",
			Handler:    _AiService_GetDraftFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
