// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: discussion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_discussion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_discussion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	InitialPost   string                 `protobuf:"bytes,5,opt,name=initial_post,json=initialPost,proto3" json:"initial_post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThreadRequest) Reset() {
	*x = CreateThreadRequest{}
	mi := &file_discussion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThreadRequest) ProtoMessage() {}

func (x *CreateThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThreadRequest.ProtoReflect.Descriptor instead.
func (*CreateThreadRequest) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{2}
}

func (x *CreateThreadRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateThreadRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateThreadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateThreadRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateThreadRequest) GetInitialPost() string {
	if x != nil {
		return x.InitialPost
	}
	return ""
}

type Thread struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId       string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActivityAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	ReplyCount     int32                  `protobuf:"varint,7,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Thread) Reset() {
	*x = Thread{}
	mi := &file_discussion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread) ProtoMessage() {}

func (x *Thread) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread.ProtoReflect.Descriptor instead.
func (*Thread) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{3}
}

func (x *Thread) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Thread) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Thread) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Thread) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Thread) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Thread) GetLastActivityAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivityAt
	}
	return nil
}

func (x *Thread) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

type ListThreadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsRequest) Reset() {
	*x = ListThreadsRequest{}
	mi := &file_discussion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsRequest) ProtoMessage() {}

func (x *ListThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsRequest.ProtoReflect.Descriptor instead.
func (*ListThreadsRequest) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{4}
}

func (x *ListThreadsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListThreadsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *ListThreadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListThreadsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*Thread              `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsResponse) Reset() {
	*x = ListThreadsResponse{}
	mi := &file_discussion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsResponse) ProtoMessage() {}

func (x *ListThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsResponse.ProtoReflect.Descriptor instead.
func (*ListThreadsResponse) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{5}
}

func (x *ListThreadsResponse) GetThreads() []*Thread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *ListThreadsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListThreadsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadRequest) Reset() {
	*x = GetThreadRequest{}
	mi := &file_discussion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadRequest) ProtoMessage() {}

func (x *GetThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadRequest.ProtoReflect.Descriptor instead.
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{6}
}

func (x *GetThreadRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

type ThreadWithPosts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thread        *Thread                `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Posts         []*Post                `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadWithPosts) Reset() {
	*x = ThreadWithPosts{}
	mi := &file_discussion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadWithPosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadWithPosts) ProtoMessage() {}

func (x *ThreadWithPosts) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadWithPosts.ProtoReflect.Descriptor instead.
func (*ThreadWithPosts) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{7}
}

func (x *ThreadWithPosts) GetThread() *Thread {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *ThreadWithPosts) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ParentPostId  string                 `protobuf:"bytes,5,opt,name=parent_post_id,json=parentPostId,proto3" json:"parent_post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_discussion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePostRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreatePostRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *CreatePostRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetParentPostId() string {
	if x != nil {
		return x.ParentPostId
	}
	return ""
}

type Post struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId         string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	AuthorId         string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content          string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ParentPostId     string                 `protobuf:"bytes,5,opt,name=parent_post_id,json=parentPostId,proto3" json:"parent_post_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EditedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	MentionedUserIds []string               `protobuf:"bytes,8,rep,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_discussion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{9}
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Post) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetParentPostId() string {
	if x != nil {
		return x.ParentPostId
	}
	return ""
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *Post) GetMentionedUserIds() []string {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

type GetInboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	UnseenOnly    bool                   `protobuf:"varint,5,opt,name=unseen_only,json=unseenOnly,proto3" json:"unseen_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboxRequest) Reset() {
	*x = GetInboxRequest{}
	mi := &file_discussion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboxRequest) ProtoMessage() {}

func (x *GetInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboxRequest.ProtoReflect.Descriptor instead.
func (*GetInboxRequest) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{10}
}

func (x *GetInboxRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetInboxRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetInboxRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetInboxRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetInboxRequest) GetUnseenOnly() bool {
	if x != nil {
		return x.UnseenOnly
	}
	return false
}

type InboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InboxItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxResponse) Reset() {
	*x = InboxResponse{}
	mi := &file_discussion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxResponse) ProtoMessage() {}

func (x *InboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxResponse.ProtoReflect.Descriptor instead.
func (*InboxResponse) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{11}
}

func (x *InboxResponse) GetItems() []*InboxItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InboxResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *InboxResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type InboxItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	SeenAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=seen_at,json=seenAt,proto3" json:"seen_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxItem) Reset() {
	*x = InboxItem{}
	mi := &file_discussion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxItem) ProtoMessage() {}

func (x *InboxItem) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxItem.ProtoReflect.Descriptor instead.
func (*InboxItem) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{12}
}

func (x *InboxItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InboxItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InboxItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InboxItem) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *InboxItem) GetSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SeenAt
	}
	return nil
}

func (x *InboxItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MarkReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	InboxItemId   string                 `protobuf:"bytes,2,opt,name=inbox_item_id,json=inboxItemId,proto3" json:"inbox_item_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_discussion_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{13}
}

func (x *MarkReadRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MarkReadRequest) GetInboxItemId() string {
	if x != nil {
		return x.InboxItemId
	}
	return ""
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListNeedingReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	InstructorId  string                 `protobuf:"bytes,2,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	CourseIds     []string               `protobuf:"bytes,3,rep,name=course_ids,json=courseIds,proto3" json:"course_ids,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNeedingReplyRequest) Reset() {
	*x = ListNeedingReplyRequest{}
	mi := &file_discussion_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNeedingReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNeedingReplyRequest) ProtoMessage() {}

func (x *ListNeedingReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discussion_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNeedingReplyRequest.ProtoReflect.Descriptor instead.
func (*ListNeedingReplyRequest) Descriptor() ([]byte, []int) {
	return file_discussion_proto_rawDescGZIP(), []int{14}
}

func (x *ListNeedingReplyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListNeedingReplyRequest) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *ListNeedingReplyRequest) GetCourseIds() []string {
	if x != nil {
		return x.CourseIds
	}
	return nil
}

func (x *ListNeedingReplyRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_discussion_proto protoreflect.FileDescriptor

const file_discussion_proto_rawDesc = "" +
	"\n" +
	"\x10discussion.proto\x12\n" +
	"discussion\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xa7\x01\n" +
	"\x13CreateThreadRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12!\n" +
	"\finitial_post\x18\x05 \x01(\tR\vinitialPost\"\x8c\x02\n" +
	"\x06Thread\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12D\n" +
	"\x10last_activity_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastActivityAt\x12\x1f\n" +
	"\vreply_count\x18\a \x01(\x05R\n" +
	"replyCount\"|\n" +
	"\x12ListThreadsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"\x7f\n" +
	"\x13ListThreadsResponse\x12,\n" +
	"\athreads\x18\x01 \x03(\v2\x12.discussion.ThreadR\athreads\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"L\n" +
	"\x10GetThreadRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"e\n" +
	"\x0fThreadWithPosts\x12*\n" +
	"\x06thread\x18\x01 \x01(\v2\x12.discussion.ThreadR\x06thread\x12&\n" +
	"\x05posts\x18\x02 \x03(\v2\x10.discussion.PostR\x05posts\"\xaa\x01\n" +
	"\x11CreatePostRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12$\n" +
	"\x0eparent_post_id\x18\x05 \x01(\tR\fparentPostId\"\xb2\x02\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12$\n" +
	"\x0eparent_post_id\x18\x05 \x01(\tR\fparentPostId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tedited_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\x12,\n" +
	"\x12mentioned_user_ids\x18\b \x03(\tR\x10mentionedUserIds\"\x96\x01\n" +
	"\x0fGetInboxRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x1f\n" +
	"\vunseen_only\x18\x05 \x01(\bR\n" +
	"unseenOnly\"x\n" +
	"\rInboxResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.discussion.InboxItemR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\xdb\x01\n" +
	"\tInboxItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\freference_id\x18\x04 \x01(\tR\vreferenceId\x123\n" +
	"\aseen_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06seenAt\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"k\n" +
	"\x0fMarkReadRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\"\n" +
	"\rinbox_item_id\x18\x02 \x01(\tR\vinboxItemId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\x90\x01\n" +
	"\x17ListNeedingReplyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12#\n" +
	"\rinstructor_id\x18\x02 \x01(\tR\finstructorId\x12\x1d\n" +
	"\n" +
	"course_ids\x18\x03 \x03(\tR\tcourseIds\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit2\xe9\x04\n" +
	"\x11DiscussionService\x12C\n" +
	"\fCreateThread\x12\x1f.discussion.CreateThreadRequest\x1a\x12.discussion.Thread\x12N\n" +
	"\vListThreads\x12\x1e.discussion.ListThreadsRequest\x1a\x1f.discussion.ListThreadsResponse\x12F\n" +
	"\tGetThread\x12\x1c.discussion.GetThreadRequest\x1a\x1b.discussion.ThreadWithPosts\x12=\n" +
	"\n" +
	"CreatePost\x12\x1d.discussion.CreatePostRequest\x1a\x10.discussion.Post\x12B\n" +
	"\bGetInbox\x12\x1b.discussion.GetInboxRequest\x1a\x19.discussion.InboxResponse\x12D\n" +
	"\rMarkInboxRead\x12\x1b.discussion.MarkReadRequest\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x16GetThreadsNeedingReply\x12#.discussion.ListNeedingReplyRequest\x1a\x1f.discussion.ListThreadsResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.discussion.HealthCheckRequest\x1a\x1f.discussion.HealthCheckResponseB-Z+slate/services/discussion-service/api/protob\x06proto3"

var (
	file_discussion_proto_rawDescOnce sync.Once
	file_discussion_proto_rawDescData []byte
)

func file_discussion_proto_rawDescGZIP() []byte {
	file_discussion_proto_rawDescOnce.Do(func() {
		file_discussion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discussion_proto_rawDesc), len(file_discussion_proto_rawDesc)))
	})
	return file_discussion_proto_rawDescData
}

var file_discussion_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_discussion_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),      // 0: discussion.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 1: discussion.HealthCheckResponse
	(*CreateThreadRequest)(nil),     // 2: discussion.CreateThreadRequest
	(*Thread)(nil),                  // 3: discussion.Thread
	(*ListThreadsRequest)(nil),      // 4: discussion.ListThreadsRequest
	(*ListThreadsResponse)(nil),     // 5: discussion.ListThreadsResponse
	(*GetThreadRequest)(nil),        // 6: discussion.GetThreadRequest
	(*ThreadWithPosts)(nil),         // 7: discussion.ThreadWithPosts
	(*CreatePostRequest)(nil),       // 8: discussion.CreatePostRequest
	(*Post)(nil),                    // 9: discussion.Post
	(*GetInboxRequest)(nil),         // 10: discussion.GetInboxRequest
	(*InboxResponse)(nil),           // 11: discussion.InboxResponse
	(*InboxItem)(nil),               // 12: discussion.InboxItem
	(*MarkReadRequest)(nil),         // 13: discussion.MarkReadRequest
	(*ListNeedingReplyRequest)(nil), // 14: discussion.ListNeedingReplyRequest
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 16: google.protobuf.Empty
}
var file_discussion_proto_depIdxs = []int32{
	15, // 0: discussion.Thread.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: discussion.Thread.last_activity_at:type_name -> google.protobuf.Timestamp
	3,  // 2: discussion.ListThreadsResponse.threads:type_name -> discussion.Thread
	3,  // 3: discussion.ThreadWithPosts.thread:type_name -> discussion.Thread
	9,  // 4: discussion.ThreadWithPosts.posts:type_name -> discussion.Post
	15, // 5: discussion.Post.created_at:type_name -> google.protobuf.Timestamp
	15, // 6: discussion.Post.edited_at:type_name -> google.protobuf.Timestamp
	12, // 7: discussion.InboxResponse.items:type_name -> discussion.InboxItem
	15, // 8: discussion.InboxItem.seen_at:type_name -> google.protobuf.Timestamp
	15, // 9: discussion.InboxItem.created_at:type_name -> google.protobuf.Timestamp
	2,  // 10: discussion.DiscussionService.CreateThread:input_type -> discussion.CreateThreadRequest
	4,  // 11: discussion.DiscussionService.ListThreads:input_type -> discussion.ListThreadsRequest
	6,  // 12: discussion.DiscussionService.GetThread:input_type -> discussion.GetThreadRequest
	8,  // 13: discussion.DiscussionService.CreatePost:input_type -> discussion.CreatePostRequest
	10, // 14: discussion.DiscussionService.GetInbox:input_type -> discussion.GetInboxRequest
	13, // 15: discussion.DiscussionService.MarkInboxRead:input_type -> discussion.MarkReadRequest
	14, // 16: discussion.DiscussionService.GetThreadsNeedingReply:input_type -> discussion.ListNeedingReplyRequest
	0,  // 17: discussion.DiscussionService.HealthCheck:input_type -> discussion.HealthCheckRequest
	3,  // 18: discussion.DiscussionService.CreateThread:output_type -> discussion.Thread
	5,  // 19: discussion.DiscussionService.ListThreads:output_type -> discussion.ListThreadsResponse
	7,  // 20: discussion.DiscussionService.GetThread:output_type -> discussion.ThreadWithPosts
	9,  // 21: discussion.DiscussionService.CreatePost:output_type -> discussion.Post
	11, // 22: discussion.DiscussionService.GetInbox:output_type -> discussion.InboxResponse
	16, // 23: discussion.DiscussionService.MarkInboxRead:output_type -> google.protobuf.Empty
	5,  // 24: discussion.DiscussionService.GetThreadsNeedingReply:output_type -> discussion.ListThreadsResponse
	1,  // 25: discussion.DiscussionService.HealthCheck:output_type -> discussion.HealthCheckResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_discussion_proto_init() }
func file_discussion_proto_init() {
	if File_discussion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discussion_proto_rawDesc), len(file_discussion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discussion_proto_goTypes,
		DependencyIndexes: file_discussion_proto_depIdxs,
		MessageInfos:      file_discussion_proto_msgTypes,
	}.Build()
	File_discussion_proto = out.File
	file_discussion_proto_goTypes = nil
	file_discussion_proto_depIdxs = nil
}
