// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: feature_flag.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlagService_EvaluateFlags_FullMethodName = "/flag.FlagService/EvaluateFlags"
	FlagService_ListFlags_FullMethodName     = "/flag.FlagService/ListFlags"
	FlagService_GetFlag_FullMethodName       = "/flag.FlagService/GetFlag"
	FlagService_UpdateFlag_FullMethodName    = "/flag.FlagService/UpdateFlag"
	FlagService_DeleteFlag_FullMethodName    = "/flag.FlagService/DeleteFlag"
)

// FlagServiceClient is the client API for FlagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FlagService — platform-level feature flag evaluator (W3).
// gRPC :50062, HTTP :8092.
type FlagServiceClient interface {
	// Gateway-hot-path. Called once per authenticated request (via Redis cache).
	EvaluateFlags(ctx context.Context, in *EvaluateFlagsRequest, opts ...grpc.CallOption) (*EvaluateFlagsResponse, error)
	// Admin-only. Backs GET /api/flags.
	ListFlags(ctx context.Context, in *ListFlagsRequest, opts ...grpc.CallOption) (*ListFlagsResponse, error)
	// Admin-only. Backs GET /api/flags/:key. Returns NotFound when the key
	// is absent so the HTTP layer can map cleanly to 404.
	GetFlag(ctx context.Context, in *GetFlagRequest, opts ...grpc.CallOption) (*Flag, error)
	// Admin-only. Backs PUT /api/flags/:key. Invalidates Redis cache on success.
	UpdateFlag(ctx context.Context, in *UpdateFlagRequest, opts ...grpc.CallOption) (*Flag, error)
	// Admin-only. Backs DELETE /api/flags/:key. Invalidates Redis cache on success.
	DeleteFlag(ctx context.Context, in *DeleteFlagRequest, opts ...grpc.CallOption) (*DeleteFlagResponse, error)
}

type flagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlagServiceClient(cc grpc.ClientConnInterface) FlagServiceClient {
	return &flagServiceClient{cc}
}

func (c *flagServiceClient) EvaluateFlags(ctx context.Context, in *EvaluateFlagsRequest, opts ...grpc.CallOption) (*EvaluateFlagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateFlagsResponse)
	err := c.cc.Invoke(ctx, FlagService_EvaluateFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagServiceClient) ListFlags(ctx context.Context, in *ListFlagsRequest, opts ...grpc.CallOption) (*ListFlagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFlagsResponse)
	err := c.cc.Invoke(ctx, FlagService_ListFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagServiceClient) GetFlag(ctx context.Context, in *GetFlagRequest, opts ...grpc.CallOption) (*Flag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Flag)
	err := c.cc.Invoke(ctx, FlagService_GetFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagServiceClient) UpdateFlag(ctx context.Context, in *UpdateFlagRequest, opts ...grpc.CallOption) (*Flag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Flag)
	err := c.cc.Invoke(ctx, FlagService_UpdateFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flagServiceClient) DeleteFlag(ctx context.Context, in *DeleteFlagRequest, opts ...grpc.CallOption) (*DeleteFlagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFlagResponse)
	err := c.cc.Invoke(ctx, FlagService_DeleteFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlagServiceServer is the server API for FlagService service.
// All implementations must embed UnimplementedFlagServiceServer
// for forward compatibility.
//
// FlagService — platform-level feature flag evaluator (W3).
// gRPC :50062, HTTP :8092.
type FlagServiceServer interface {
	// Gateway-hot-path. Called once per authenticated request (via Redis cache).
	EvaluateFlags(context.Context, *EvaluateFlagsRequest) (*EvaluateFlagsResponse, error)
	// Admin-only. Backs GET /api/flags.
	ListFlags(context.Context, *ListFlagsRequest) (*ListFlagsResponse, error)
	// Admin-only. Backs GET /api/flags/:key. Returns NotFound when the key
	// is absent so the HTTP layer can map cleanly to 404.
	GetFlag(context.Context, *GetFlagRequest) (*Flag, error)
	// Admin-only. Backs PUT /api/flags/:key. Invalidates Redis cache on success.
	UpdateFlag(context.Context, *UpdateFlagRequest) (*Flag, error)
	// Admin-only. Backs DELETE /api/flags/:key. Invalidates Redis cache on success.
	DeleteFlag(context.Context, *DeleteFlagRequest) (*DeleteFlagResponse, error)
	mustEmbedUnimplementedFlagServiceServer()
}

// UnimplementedFlagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlagServiceServer struct{}

func (UnimplementedFlagServiceServer) EvaluateFlags(context.Context, *EvaluateFlagsRequest) (*EvaluateFlagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateFlags not implemented")
}
func (UnimplementedFlagServiceServer) ListFlags(context.Context, *ListFlagsRequest) (*ListFlagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFlags not implemented")
}
func (UnimplementedFlagServiceServer) GetFlag(context.Context, *GetFlagRequest) (*Flag, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFlag not implemented")
}
func (UnimplementedFlagServiceServer) UpdateFlag(context.Context, *UpdateFlagRequest) (*Flag, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFlag not implemented")
}
func (UnimplementedFlagServiceServer) DeleteFlag(context.Context, *DeleteFlagRequest) (*DeleteFlagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFlag not implemented")
}
func (UnimplementedFlagServiceServer) mustEmbedUnimplementedFlagServiceServer() {}
func (UnimplementedFlagServiceServer) testEmbeddedByValue()                     {}

// UnsafeFlagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlagServiceServer will
// result in compilation errors.
type UnsafeFlagServiceServer interface {
	mustEmbedUnimplementedFlagServiceServer()
}

func RegisterFlagServiceServer(s grpc.ServiceRegistrar, srv FlagServiceServer) {
	// If the following call panics, it indicates UnimplementedFlagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlagService_ServiceDesc, srv)
}

func _FlagService_EvaluateFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateFlagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlagServiceServer).EvaluateFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlagService_EvaluateFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlagServiceServer).EvaluateFlags(ctx, req.(*EvaluateFlagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlagService_ListFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlagServiceServer).ListFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlagService_ListFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlagServiceServer).ListFlags(ctx, req.(*ListFlagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlagService_GetFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlagServiceServer).GetFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlagService_GetFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlagServiceServer).GetFlag(ctx, req.(*GetFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlagService_UpdateFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlagServiceServer).UpdateFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlagService_UpdateFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlagServiceServer).UpdateFlag(ctx, req.(*UpdateFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlagService_DeleteFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlagServiceServer).DeleteFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlagService_DeleteFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlagServiceServer).DeleteFlag(ctx, req.(*DeleteFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlagService_ServiceDesc is the grpc.ServiceDesc for FlagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flag.FlagService",
	HandlerType: (*FlagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateFlags",
			Handler:    _FlagService_EvaluateFlags_Handler,
		},
		{
			MethodName: "ListFlags",
			Handler:    _FlagService_ListFlags_Handler,
		},
		{
			MethodName: "GetFlag",
			Handler:    _FlagService_GetFlag_Handler,
		},
		{
			MethodName: "UpdateFlag",
			Handler:    _FlagService_UpdateFlag_Handler,
		},
		{
			MethodName: "DeleteFlag",
			Handler:    _FlagService_DeleteFlag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feature_flag.proto",
}
