// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: feature_flag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateFlagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantSlug    string                 `protobuf:"bytes,2,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateFlagsRequest) Reset() {
	*x = EvaluateFlagsRequest{}
	mi := &file_feature_flag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFlagsRequest) ProtoMessage() {}

func (x *EvaluateFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFlagsRequest.ProtoReflect.Descriptor instead.
func (*EvaluateFlagsRequest) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateFlagsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EvaluateFlagsRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *EvaluateFlagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EvaluateFlagsRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type EvaluateFlagsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Flags             map[string]bool        `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	EvaluatedAtUnixMs int64                  `protobuf:"varint,2,opt,name=evaluated_at_unix_ms,json=evaluatedAtUnixMs,proto3" json:"evaluated_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EvaluateFlagsResponse) Reset() {
	*x = EvaluateFlagsResponse{}
	mi := &file_feature_flag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFlagsResponse) ProtoMessage() {}

func (x *EvaluateFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFlagsResponse.ProtoReflect.Descriptor instead.
func (*EvaluateFlagsResponse) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateFlagsResponse) GetFlags() map[string]bool {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *EvaluateFlagsResponse) GetEvaluatedAtUnixMs() int64 {
	if x != nil {
		return x.EvaluatedAtUnixMs
	}
	return 0
}

type ListFlagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlagsRequest) Reset() {
	*x = ListFlagsRequest{}
	mi := &file_feature_flag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagsRequest) ProtoMessage() {}

func (x *ListFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagsRequest.ProtoReflect.Descriptor instead.
func (*ListFlagsRequest) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{2}
}

func (x *ListFlagsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagRequest) Reset() {
	*x = GetFlagRequest{}
	mi := &file_feature_flag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagRequest) ProtoMessage() {}

func (x *GetFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagRequest.ProtoReflect.Descriptor instead.
func (*GetFlagRequest) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{3}
}

func (x *GetFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetFlagRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListFlagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         []*Flag                `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlagsResponse) Reset() {
	*x = ListFlagsResponse{}
	mi := &file_feature_flag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlagsResponse) ProtoMessage() {}

func (x *ListFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlagsResponse.ProtoReflect.Descriptor instead.
func (*ListFlagsResponse) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{4}
}

func (x *ListFlagsResponse) GetFlags() []*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type Flag struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	State           bool                   `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	Targets         []*TargetRule          `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,5,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_feature_flag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{5}
}

func (x *Flag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Flag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flag) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *Flag) GetTargets() []*TargetRule {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Flag) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

type TargetRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rule types per plan W3.2: "all" | "tenant" | "role" | "percentage" | "user".
	RuleType string `protobuf:"bytes,1,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	// JSON-encoded value matching rule_type, e.g. {"roles":["instructor"]} or {"percent":50}.
	RuleValueJson string `protobuf:"bytes,2,opt,name=rule_value_json,json=ruleValueJson,proto3" json:"rule_value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRule) Reset() {
	*x = TargetRule{}
	mi := &file_feature_flag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRule) ProtoMessage() {}

func (x *TargetRule) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRule.ProtoReflect.Descriptor instead.
func (*TargetRule) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{6}
}

func (x *TargetRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *TargetRule) GetRuleValueJson() string {
	if x != nil {
		return x.RuleValueJson
	}
	return ""
}

type UpdateFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	State         bool                   `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Targets       []*TargetRule          `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFlagRequest) Reset() {
	*x = UpdateFlagRequest{}
	mi := &file_feature_flag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlagRequest) ProtoMessage() {}

func (x *UpdateFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlagRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlagRequest) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateFlagRequest) GetState() bool {
	if x != nil {
		return x.State
	}
	return false
}

func (x *UpdateFlagRequest) GetTargets() []*TargetRule {
	if x != nil {
		return x.Targets
	}
	return nil
}

type DeleteFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlagRequest) Reset() {
	*x = DeleteFlagRequest{}
	mi := &file_feature_flag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlagRequest) ProtoMessage() {}

func (x *DeleteFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlagRequest.ProtoReflect.Descriptor instead.
func (*DeleteFlagRequest) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteFlagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlagResponse) Reset() {
	*x = DeleteFlagResponse{}
	mi := &file_feature_flag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlagResponse) ProtoMessage() {}

func (x *DeleteFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feature_flag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlagResponse.ProtoReflect.Descriptor instead.
func (*DeleteFlagResponse) Descriptor() ([]byte, []int) {
	return file_feature_flag_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFlagResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_feature_flag_proto protoreflect.FileDescriptor

const file_feature_flag_proto_rawDesc = "" +
	"\n" +
	"\x12feature_flag.proto\x12\x04flag\"\x83\x01\n" +
	"\x14EvaluateFlagsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_slug\x18\x02 \x01(\tR\n" +
	"tenantSlug\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"\xc0\x01\n" +
	"\x15EvaluateFlagsResponse\x12<\n" +
	"\x05flags\x18\x01 \x03(\v2&.flag.EvaluateFlagsResponse.FlagsEntryR\x05flags\x12/\n" +
	"\x14evaluated_at_unix_ms\x18\x02 \x01(\x03R\x11evaluatedAtUnixMs\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"/\n" +
	"\x10ListFlagsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"?\n" +
	"\x0eGetFlagRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"5\n" +
	"\x11ListFlagsResponse\x12 \n" +
	"\x05flags\x18\x01 \x03(\v2\n" +
	".flag.FlagR\x05flags\"\xa9\x01\n" +
	"\x04Flag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05state\x18\x03 \x01(\bR\x05state\x12*\n" +
	"\atargets\x18\x04 \x03(\v2\x10.flag.TargetRuleR\atargets\x12+\n" +
	"\x12updated_at_unix_ms\x18\x05 \x01(\x03R\x0fupdatedAtUnixMs\"Q\n" +
	"\n" +
	"TargetRule\x12\x1b\n" +
	"\trule_type\x18\x01 \x01(\tR\bruleType\x12&\n" +
	"\x0frule_value_json\x18\x02 \x01(\tR\rruleValueJson\"g\n" +
	"\x11UpdateFlagRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05state\x18\x02 \x01(\bR\x05state\x12*\n" +
	"\atargets\x18\x03 \x03(\v2\x10.flag.TargetRuleR\atargets\"%\n" +
	"\x11DeleteFlagRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\".\n" +
	"\x12DeleteFlagResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\xb6\x02\n" +
	"\vFlagService\x12H\n" +
	"\rEvaluateFlags\x12\x1a.flag.EvaluateFlagsRequest\x1a\x1b.flag.EvaluateFlagsResponse\x12<\n" +
	"\tListFlags\x12\x16.flag.ListFlagsRequest\x1a\x17.flag.ListFlagsResponse\x12+\n" +
	"\aGetFlag\x12\x14.flag.GetFlagRequest\x1a\n" +
	".flag.Flag\x121\n" +
	"\n" +
	"UpdateFlag\x12\x17.flag.UpdateFlagRequest\x1a\n" +
	".flag.Flag\x12?\n" +
	"\n" +
	"DeleteFlag\x12\x17.flag.DeleteFlagRequest\x1a\x18.flag.DeleteFlagResponseB/Z-slate/services/feature-flag-service/api/protob\x06proto3"

var (
	file_feature_flag_proto_rawDescOnce sync.Once
	file_feature_flag_proto_rawDescData []byte
)

func file_feature_flag_proto_rawDescGZIP() []byte {
	file_feature_flag_proto_rawDescOnce.Do(func() {
		file_feature_flag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feature_flag_proto_rawDesc), len(file_feature_flag_proto_rawDesc)))
	})
	return file_feature_flag_proto_rawDescData
}

var file_feature_flag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_feature_flag_proto_goTypes = []any{
	(*EvaluateFlagsRequest)(nil),  // 0: flag.EvaluateFlagsRequest
	(*EvaluateFlagsResponse)(nil), // 1: flag.EvaluateFlagsResponse
	(*ListFlagsRequest)(nil),      // 2: flag.ListFlagsRequest
	(*GetFlagRequest)(nil),        // 3: flag.GetFlagRequest
	(*ListFlagsResponse)(nil),     // 4: flag.ListFlagsResponse
	(*Flag)(nil),                  // 5: flag.Flag
	(*TargetRule)(nil),            // 6: flag.TargetRule
	(*UpdateFlagRequest)(nil),     // 7: flag.UpdateFlagRequest
	(*DeleteFlagRequest)(nil),     // 8: flag.DeleteFlagRequest
	(*DeleteFlagResponse)(nil),    // 9: flag.DeleteFlagResponse
	nil,                           // 10: flag.EvaluateFlagsResponse.FlagsEntry
}
var file_feature_flag_proto_depIdxs = []int32{
	10, // 0: flag.EvaluateFlagsResponse.flags:type_name -> flag.EvaluateFlagsResponse.FlagsEntry
	5,  // 1: flag.ListFlagsResponse.flags:type_name -> flag.Flag
	6,  // 2: flag.Flag.targets:type_name -> flag.TargetRule
	6,  // 3: flag.UpdateFlagRequest.targets:type_name -> flag.TargetRule
	0,  // 4: flag.FlagService.EvaluateFlags:input_type -> flag.EvaluateFlagsRequest
	2,  // 5: flag.FlagService.ListFlags:input_type -> flag.ListFlagsRequest
	3,  // 6: flag.FlagService.GetFlag:input_type -> flag.GetFlagRequest
	7,  // 7: flag.FlagService.UpdateFlag:input_type -> flag.UpdateFlagRequest
	8,  // 8: flag.FlagService.DeleteFlag:input_type -> flag.DeleteFlagRequest
	1,  // 9: flag.FlagService.EvaluateFlags:output_type -> flag.EvaluateFlagsResponse
	4,  // 10: flag.FlagService.ListFlags:output_type -> flag.ListFlagsResponse
	5,  // 11: flag.FlagService.GetFlag:output_type -> flag.Flag
	5,  // 12: flag.FlagService.UpdateFlag:output_type -> flag.Flag
	9,  // 13: flag.FlagService.DeleteFlag:output_type -> flag.DeleteFlagResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_feature_flag_proto_init() }
func file_feature_flag_proto_init() {
	if File_feature_flag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feature_flag_proto_rawDesc), len(file_feature_flag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feature_flag_proto_goTypes,
		DependencyIndexes: file_feature_flag_proto_depIdxs,
		MessageInfos:      file_feature_flag_proto_msgTypes,
	}.Build()
	File_feature_flag_proto = out.File
	file_feature_flag_proto_goTypes = nil
	file_feature_flag_proto_depIdxs = nil
}
