// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: scheduling.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Schedule struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstructorId        string                 `protobuf:"bytes,2,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	DayOfWeek           int32                  `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"` // 0=Sunday ... 6=Saturday
	StartTime           string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`    // "HH:MM" 24-hour
	EndTime             string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`          // "HH:MM"
	SlotDurationMinutes int32                  `protobuf:"varint,6,opt,name=slot_duration_minutes,json=slotDurationMinutes,proto3" json:"slot_duration_minutes,omitempty"`
	Format              string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"` // "online" | "in_person"
	Location            string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	IsActive            bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_scheduling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{0}
}

func (x *Schedule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Schedule) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *Schedule) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *Schedule) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Schedule) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Schedule) GetSlotDurationMinutes() int32 {
	if x != nil {
		return x.SlotDurationMinutes
	}
	return 0
}

func (x *Schedule) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Schedule) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Schedule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Schedule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateScheduleRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug          string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	InstructorId        string                 `protobuf:"bytes,2,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	DayOfWeek           int32                  `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime           string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SlotDurationMinutes int32                  `protobuf:"varint,6,opt,name=slot_duration_minutes,json=slotDurationMinutes,proto3" json:"slot_duration_minutes,omitempty"`
	Format              string                 `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	Location            string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_scheduling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScheduleRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *CreateScheduleRequest) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *CreateScheduleRequest) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *CreateScheduleRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateScheduleRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateScheduleRequest) GetSlotDurationMinutes() int32 {
	if x != nil {
		return x.SlotDurationMinutes
	}
	return 0
}

func (x *CreateScheduleRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CreateScheduleRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ListSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	InstructorId  string                 `protobuf:"bytes,2,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,3,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_scheduling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{2}
}

func (x *ListSchedulesRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *ListSchedulesRequest) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *ListSchedulesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*Schedule            `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_scheduling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{3}
}

func (x *ListSchedulesResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type ListSlotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	InstructorId  string                 `protobuf:"bytes,2,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"` // "YYYY-MM-DD"
	DateTo        string                 `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`       // "YYYY-MM-DD" inclusive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlotsRequest) Reset() {
	*x = ListSlotsRequest{}
	mi := &file_scheduling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlotsRequest) ProtoMessage() {}

func (x *ListSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlotsRequest.ProtoReflect.Descriptor instead.
func (*ListSlotsRequest) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{4}
}

func (x *ListSlotsRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *ListSlotsRequest) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *ListSlotsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *ListSlotsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	InstructorId  string                 `protobuf:"bytes,2,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	SlotDate      string                 `protobuf:"bytes,3,opt,name=slot_date,json=slotDate,proto3" json:"slot_date,omitempty"`                  // "YYYY-MM-DD"
	SlotStartTime string                 `protobuf:"bytes,4,opt,name=slot_start_time,json=slotStartTime,proto3" json:"slot_start_time,omitempty"` // "HH:MM"
	SlotEndTime   string                 `protobuf:"bytes,5,opt,name=slot_end_time,json=slotEndTime,proto3" json:"slot_end_time,omitempty"`       // "HH:MM"
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_scheduling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{5}
}

func (x *Slot) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Slot) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *Slot) GetSlotDate() string {
	if x != nil {
		return x.SlotDate
	}
	return ""
}

func (x *Slot) GetSlotStartTime() string {
	if x != nil {
		return x.SlotStartTime
	}
	return ""
}

func (x *Slot) GetSlotEndTime() string {
	if x != nil {
		return x.SlotEndTime
	}
	return ""
}

func (x *Slot) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Slot) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ListSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*Slot                `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	FromCache     bool                   `protobuf:"varint,2,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlotsResponse) Reset() {
	*x = ListSlotsResponse{}
	mi := &file_scheduling_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlotsResponse) ProtoMessage() {}

func (x *ListSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlotsResponse.ProtoReflect.Descriptor instead.
func (*ListSlotsResponse) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{6}
}

func (x *ListSlotsResponse) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *ListSlotsResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type BookSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	InstructorId  string                 `protobuf:"bytes,3,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,4,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	SlotDate      string                 `protobuf:"bytes,5,opt,name=slot_date,json=slotDate,proto3" json:"slot_date,omitempty"`                  // "YYYY-MM-DD"
	SlotStartTime string                 `protobuf:"bytes,6,opt,name=slot_start_time,json=slotStartTime,proto3" json:"slot_start_time,omitempty"` // "HH:MM"
	PreContext    string                 `protobuf:"bytes,7,opt,name=pre_context,json=preContext,proto3" json:"pre_context,omitempty"`            // student's current assignment / draft question
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSlotRequest) Reset() {
	*x = BookSlotRequest{}
	mi := &file_scheduling_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSlotRequest) ProtoMessage() {}

func (x *BookSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSlotRequest.ProtoReflect.Descriptor instead.
func (*BookSlotRequest) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{7}
}

func (x *BookSlotRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *BookSlotRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *BookSlotRequest) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *BookSlotRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *BookSlotRequest) GetSlotDate() string {
	if x != nil {
		return x.SlotDate
	}
	return ""
}

func (x *BookSlotRequest) GetSlotStartTime() string {
	if x != nil {
		return x.SlotStartTime
	}
	return ""
}

func (x *BookSlotRequest) GetPreContext() string {
	if x != nil {
		return x.PreContext
	}
	return ""
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	InstructorId  string                 `protobuf:"bytes,3,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,4,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	SlotDate      string                 `protobuf:"bytes,5,opt,name=slot_date,json=slotDate,proto3" json:"slot_date,omitempty"`
	SlotStartTime string                 `protobuf:"bytes,6,opt,name=slot_start_time,json=slotStartTime,proto3" json:"slot_start_time,omitempty"`
	Questions     string                 `protobuf:"bytes,7,opt,name=questions,proto3" json:"questions,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // "confirmed" | "cancelled"
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_scheduling_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{8}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Booking) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *Booking) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Booking) GetSlotDate() string {
	if x != nil {
		return x.SlotDate
	}
	return ""
}

func (x *Booking) GetSlotStartTime() string {
	if x != nil {
		return x.SlotStartTime
	}
	return ""
}

func (x *Booking) GetQuestions() string {
	if x != nil {
		return x.Questions
	}
	return ""
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"` // audit / authorization hint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_scheduling_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{9}
}

func (x *CancelBookingRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CancelBookingRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetInstructorDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantSlug    string                 `protobuf:"bytes,1,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	InstructorId  string                 `protobuf:"bytes,2,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	SlotDate      string                 `protobuf:"bytes,3,opt,name=slot_date,json=slotDate,proto3" json:"slot_date,omitempty"` // "YYYY-MM-DD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstructorDayRequest) Reset() {
	*x = GetInstructorDayRequest{}
	mi := &file_scheduling_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstructorDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstructorDayRequest) ProtoMessage() {}

func (x *GetInstructorDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstructorDayRequest.ProtoReflect.Descriptor instead.
func (*GetInstructorDayRequest) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{10}
}

func (x *GetInstructorDayRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *GetInstructorDayRequest) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *GetInstructorDayRequest) GetSlotDate() string {
	if x != nil {
		return x.SlotDate
	}
	return ""
}

type InstructorDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructorId  string                 `protobuf:"bytes,1,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	SlotDate      string                 `protobuf:"bytes,2,opt,name=slot_date,json=slotDate,proto3" json:"slot_date,omitempty"`
	Bookings      []*Booking             `protobuf:"bytes,3,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructorDayResponse) Reset() {
	*x = InstructorDayResponse{}
	mi := &file_scheduling_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructorDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructorDayResponse) ProtoMessage() {}

func (x *InstructorDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructorDayResponse.ProtoReflect.Descriptor instead.
func (*InstructorDayResponse) Descriptor() ([]byte, []int) {
	return file_scheduling_proto_rawDescGZIP(), []int{11}
}

func (x *InstructorDayResponse) GetInstructorId() string {
	if x != nil {
		return x.InstructorId
	}
	return ""
}

func (x *InstructorDayResponse) GetSlotDate() string {
	if x != nil {
		return x.SlotDate
	}
	return ""
}

func (x *InstructorDayResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

var File_scheduling_proto protoreflect.FileDescriptor

const file_scheduling_proto_rawDesc = "" +
	"\n" +
	"\x10scheduling.proto\x12\n" +
	"scheduling\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd9\x02\n" +
	"\bSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rinstructor_id\x18\x02 \x01(\tR\finstructorId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x122\n" +
	"\x15slot_duration_minutes\x18\x06 \x01(\x05R\x13slotDurationMinutes\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9f\x02\n" +
	"\x15CreateScheduleRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12#\n" +
	"\rinstructor_id\x18\x02 \x01(\tR\finstructorId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x122\n" +
	"\x15slot_duration_minutes\x18\x06 \x01(\x05R\x13slotDurationMinutes\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\"}\n" +
	"\x14ListSchedulesRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12#\n" +
	"\rinstructor_id\x18\x02 \x01(\tR\finstructorId\x12\x1f\n" +
	"\vactive_only\x18\x03 \x01(\bR\n" +
	"activeOnly\"K\n" +
	"\x15ListSchedulesResponse\x122\n" +
	"\tschedules\x18\x01 \x03(\v2\x14.scheduling.ScheduleR\tschedules\"\x8e\x01\n" +
	"\x10ListSlotsRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12#\n" +
	"\rinstructor_id\x18\x02 \x01(\tR\finstructorId\x12\x1b\n" +
	"\tdate_from\x18\x03 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x04 \x01(\tR\x06dateTo\"\xe9\x01\n" +
	"\x04Slot\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12#\n" +
	"\rinstructor_id\x18\x02 \x01(\tR\finstructorId\x12\x1b\n" +
	"\tslot_date\x18\x03 \x01(\tR\bslotDate\x12&\n" +
	"\x0fslot_start_time\x18\x04 \x01(\tR\rslotStartTime\x12\"\n" +
	"\rslot_end_time\x18\x05 \x01(\tR\vslotEndTime\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\"Z\n" +
	"\x11ListSlotsResponse\x12&\n" +
	"\x05slots\x18\x01 \x03(\v2\x10.scheduling.SlotR\x05slots\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x02 \x01(\bR\tfromCache\"\xfd\x01\n" +
	"\x0fBookSlotRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12#\n" +
	"\rinstructor_id\x18\x03 \x01(\tR\finstructorId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x04 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tslot_date\x18\x05 \x01(\tR\bslotDate\x12&\n" +
	"\x0fslot_start_time\x18\x06 \x01(\tR\rslotStartTime\x12\x1f\n" +
	"\vpre_context\x18\a \x01(\tR\n" +
	"preContext\"\xb4\x02\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12#\n" +
	"\rinstructor_id\x18\x03 \x01(\tR\finstructorId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x04 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tslot_date\x18\x05 \x01(\tR\bslotDate\x12&\n" +
	"\x0fslot_start_time\x18\x06 \x01(\tR\rslotStartTime\x12\x1c\n" +
	"\tquestions\x18\a \x01(\tR\tquestions\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"u\n" +
	"\x14CancelBookingRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\"|\n" +
	"\x17GetInstructorDayRequest\x12\x1f\n" +
	"\vtenant_slug\x18\x01 \x01(\tR\n" +
	"tenantSlug\x12#\n" +
	"\rinstructor_id\x18\x02 \x01(\tR\finstructorId\x12\x1b\n" +
	"\tslot_date\x18\x03 \x01(\tR\bslotDate\"\x8a\x01\n" +
	"\x15InstructorDayResponse\x12#\n" +
	"\rinstructor_id\x18\x01 \x01(\tR\finstructorId\x12\x1b\n" +
	"\tslot_date\x18\x02 \x01(\tR\bslotDate\x12/\n" +
	"\bbookings\x18\x03 \x03(\v2\x13.scheduling.BookingR\bbookings2\xec\x03\n" +
	"\x11SchedulingService\x12I\n" +
	"\x0eCreateSchedule\x12!.scheduling.CreateScheduleRequest\x1a\x14.scheduling.Schedule\x12T\n" +
	"\rListSchedules\x12 .scheduling.ListSchedulesRequest\x1a!.scheduling.ListSchedulesResponse\x12Q\n" +
	"\x12ListAvailableSlots\x12\x1c.scheduling.ListSlotsRequest\x1a\x1d.scheduling.ListSlotsResponse\x12<\n" +
	"\bBookSlot\x12\x1b.scheduling.BookSlotRequest\x1a\x13.scheduling.Booking\x12I\n" +
	"\rCancelBooking\x12 .scheduling.CancelBookingRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\x10GetInstructorDay\x12#.scheduling.GetInstructorDayRequest\x1a!.scheduling.InstructorDayResponseB3Z1slate/services/scheduling-service/api/proto;protob\x06proto3"

var (
	file_scheduling_proto_rawDescOnce sync.Once
	file_scheduling_proto_rawDescData []byte
)

func file_scheduling_proto_rawDescGZIP() []byte {
	file_scheduling_proto_rawDescOnce.Do(func() {
		file_scheduling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduling_proto_rawDesc), len(file_scheduling_proto_rawDesc)))
	})
	return file_scheduling_proto_rawDescData
}

var file_scheduling_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_scheduling_proto_goTypes = []any{
	(*Schedule)(nil),                // 0: scheduling.Schedule
	(*CreateScheduleRequest)(nil),   // 1: scheduling.CreateScheduleRequest
	(*ListSchedulesRequest)(nil),    // 2: scheduling.ListSchedulesRequest
	(*ListSchedulesResponse)(nil),   // 3: scheduling.ListSchedulesResponse
	(*ListSlotsRequest)(nil),        // 4: scheduling.ListSlotsRequest
	(*Slot)(nil),                    // 5: scheduling.Slot
	(*ListSlotsResponse)(nil),       // 6: scheduling.ListSlotsResponse
	(*BookSlotRequest)(nil),         // 7: scheduling.BookSlotRequest
	(*Booking)(nil),                 // 8: scheduling.Booking
	(*CancelBookingRequest)(nil),    // 9: scheduling.CancelBookingRequest
	(*GetInstructorDayRequest)(nil), // 10: scheduling.GetInstructorDayRequest
	(*InstructorDayResponse)(nil),   // 11: scheduling.InstructorDayResponse
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 13: google.protobuf.Empty
}
var file_scheduling_proto_depIdxs = []int32{
	12, // 0: scheduling.Schedule.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: scheduling.ListSchedulesResponse.schedules:type_name -> scheduling.Schedule
	5,  // 2: scheduling.ListSlotsResponse.slots:type_name -> scheduling.Slot
	12, // 3: scheduling.Booking.created_at:type_name -> google.protobuf.Timestamp
	8,  // 4: scheduling.InstructorDayResponse.bookings:type_name -> scheduling.Booking
	1,  // 5: scheduling.SchedulingService.CreateSchedule:input_type -> scheduling.CreateScheduleRequest
	2,  // 6: scheduling.SchedulingService.ListSchedules:input_type -> scheduling.ListSchedulesRequest
	4,  // 7: scheduling.SchedulingService.ListAvailableSlots:input_type -> scheduling.ListSlotsRequest
	7,  // 8: scheduling.SchedulingService.BookSlot:input_type -> scheduling.BookSlotRequest
	9,  // 9: scheduling.SchedulingService.CancelBooking:input_type -> scheduling.CancelBookingRequest
	10, // 10: scheduling.SchedulingService.GetInstructorDay:input_type -> scheduling.GetInstructorDayRequest
	0,  // 11: scheduling.SchedulingService.CreateSchedule:output_type -> scheduling.Schedule
	3,  // 12: scheduling.SchedulingService.ListSchedules:output_type -> scheduling.ListSchedulesResponse
	6,  // 13: scheduling.SchedulingService.ListAvailableSlots:output_type -> scheduling.ListSlotsResponse
	8,  // 14: scheduling.SchedulingService.BookSlot:output_type -> scheduling.Booking
	13, // 15: scheduling.SchedulingService.CancelBooking:output_type -> google.protobuf.Empty
	11, // 16: scheduling.SchedulingService.GetInstructorDay:output_type -> scheduling.InstructorDayResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_scheduling_proto_init() }
func file_scheduling_proto_init() {
	if File_scheduling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduling_proto_rawDesc), len(file_scheduling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduling_proto_goTypes,
		DependencyIndexes: file_scheduling_proto_depIdxs,
		MessageInfos:      file_scheduling_proto_msgTypes,
	}.Build()
	File_scheduling_proto = out.File
	file_scheduling_proto_goTypes = nil
	file_scheduling_proto_depIdxs = nil
}
