// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: scheduling.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulingService_CreateSchedule_FullMethodName     = "/scheduling.SchedulingService/CreateSchedule"
	SchedulingService_ListSchedules_FullMethodName      = "/scheduling.SchedulingService/ListSchedules"
	SchedulingService_ListAvailableSlots_FullMethodName = "/scheduling.SchedulingService/ListAvailableSlots"
	SchedulingService_BookSlot_FullMethodName           = "/scheduling.SchedulingService/BookSlot"
	SchedulingService_CancelBooking_FullMethodName      = "/scheduling.SchedulingService/CancelBooking"
	SchedulingService_GetInstructorDay_FullMethodName   = "/scheduling.SchedulingService/GetInstructorDay"
)

// SchedulingServiceClient is the client API for SchedulingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SchedulingService — tenant-level office-hours + appointment booking (W6).
// gRPC :50063. One container per tenant ("scheduling-{slug}").
type SchedulingServiceClient interface {
	CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*Schedule, error)
	ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error)
	ListAvailableSlots(ctx context.Context, in *ListSlotsRequest, opts ...grpc.CallOption) (*ListSlotsResponse, error)
	BookSlot(ctx context.Context, in *BookSlotRequest, opts ...grpc.CallOption) (*Booking, error)
	CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetInstructorDay(ctx context.Context, in *GetInstructorDayRequest, opts ...grpc.CallOption) (*InstructorDayResponse, error)
}

type schedulingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingServiceClient(cc grpc.ClientConnInterface) SchedulingServiceClient {
	return &schedulingServiceClient{cc}
}

func (c *schedulingServiceClient) CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*Schedule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Schedule)
	err := c.cc.Invoke(ctx, SchedulingService_CreateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchedulesResponse)
	err := c.cc.Invoke(ctx, SchedulingService_ListSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) ListAvailableSlots(ctx context.Context, in *ListSlotsRequest, opts ...grpc.CallOption) (*ListSlotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSlotsResponse)
	err := c.cc.Invoke(ctx, SchedulingService_ListAvailableSlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) BookSlot(ctx context.Context, in *BookSlotRequest, opts ...grpc.CallOption) (*Booking, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Booking)
	err := c.cc.Invoke(ctx, SchedulingService_BookSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SchedulingService_CancelBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) GetInstructorDay(ctx context.Context, in *GetInstructorDayRequest, opts ...grpc.CallOption) (*InstructorDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstructorDayResponse)
	err := c.cc.Invoke(ctx, SchedulingService_GetInstructorDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingServiceServer is the server API for SchedulingService service.
// All implementations must embed UnimplementedSchedulingServiceServer
// for forward compatibility.
//
// SchedulingService — tenant-level office-hours + appointment booking (W6).
// gRPC :50063. One container per tenant ("scheduling-{slug}").
type SchedulingServiceServer interface {
	CreateSchedule(context.Context, *CreateScheduleRequest) (*Schedule, error)
	ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error)
	ListAvailableSlots(context.Context, *ListSlotsRequest) (*ListSlotsResponse, error)
	BookSlot(context.Context, *BookSlotRequest) (*Booking, error)
	CancelBooking(context.Context, *CancelBookingRequest) (*emptypb.Empty, error)
	GetInstructorDay(context.Context, *GetInstructorDayRequest) (*InstructorDayResponse, error)
	mustEmbedUnimplementedSchedulingServiceServer()
}

// UnimplementedSchedulingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulingServiceServer struct{}

func (UnimplementedSchedulingServiceServer) CreateSchedule(context.Context, *CreateScheduleRequest) (*Schedule, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (UnimplementedSchedulingServiceServer) ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSchedules not implemented")
}
func (UnimplementedSchedulingServiceServer) ListAvailableSlots(context.Context, *ListSlotsRequest) (*ListSlotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailableSlots not implemented")
}
func (UnimplementedSchedulingServiceServer) BookSlot(context.Context, *BookSlotRequest) (*Booking, error) {
	return nil, status.Error(codes.Unimplemented, "method BookSlot not implemented")
}
func (UnimplementedSchedulingServiceServer) CancelBooking(context.Context, *CancelBookingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBooking not implemented")
}
func (UnimplementedSchedulingServiceServer) GetInstructorDay(context.Context, *GetInstructorDayRequest) (*InstructorDayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstructorDay not implemented")
}
func (UnimplementedSchedulingServiceServer) mustEmbedUnimplementedSchedulingServiceServer() {}
func (UnimplementedSchedulingServiceServer) testEmbeddedByValue()                           {}

// UnsafeSchedulingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingServiceServer will
// result in compilation errors.
type UnsafeSchedulingServiceServer interface {
	mustEmbedUnimplementedSchedulingServiceServer()
}

func RegisterSchedulingServiceServer(s grpc.ServiceRegistrar, srv SchedulingServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulingService_ServiceDesc, srv)
}

func _SchedulingService_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_CreateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).CreateSchedule(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_ListSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListSchedules(ctx, req.(*ListSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_ListAvailableSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).ListAvailableSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_ListAvailableSlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).ListAvailableSlots(ctx, req.(*ListSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_BookSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).BookSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_BookSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).BookSlot(ctx, req.(*BookSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_CancelBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).CancelBooking(ctx, req.(*CancelBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_GetInstructorDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstructorDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).GetInstructorDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_GetInstructorDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).GetInstructorDay(ctx, req.(*GetInstructorDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulingService_ServiceDesc is the grpc.ServiceDesc for SchedulingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduling.SchedulingService",
	HandlerType: (*SchedulingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSchedule",
			Handler:    _SchedulingService_CreateSchedule_Handler,
		},
		{
			MethodName: "ListSchedules",
			Handler:    _SchedulingService_ListSchedules_Handler,
		},
		{
			MethodName: "ListAvailableSlots",
			Handler:    _SchedulingService_ListAvailableSlots_Handler,
		},
		{
			MethodName: "BookSlot",
			Handler:    _SchedulingService_BookSlot_Handler,
		},
		{
			MethodName: "CancelBooking",
			Handler:    _SchedulingService_CancelBooking_Handler,
		},
		{
			MethodName: "GetInstructorDay",
			Handler:    _SchedulingService_GetInstructorDay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduling.proto",
}
