// Package traefik writes per-tenant Traefik dynamic configuration AND the
// companion tenant endpoints yaml consumed by the api-gateway.
//
// Two files per tenant:
//
//  1. `{configDir}/tenant-{id}.yml` — Traefik router/middleware/service
//     config. Traefik watches the directory and hot-reloads on change.
//
//  2. `{tenantsDir}/{slug}.yaml` — human-authored endpoints table per
//     plan W16.3. api-gateway reads this to dispatch to the correct
//     per-tenant container (hostnames like `user-auth-{slug}:50051`).
package traefik

import (
	"fmt"
	"os"
	"path/filepath"
)

// Generator writes per-tenant Traefik dynamic config files.
type Generator struct {
	configDir  string
	tenantsDir string
}

// NewGenerator creates a Generator that writes Traefik YAML to configDir and
// the per-tenant endpoints YAML to tenantsDir.
func NewGenerator(configDir string) *Generator {
	return &Generator{configDir: configDir, tenantsDir: "config/tenants"}
}

// NewGeneratorWithTenants wires both output directories explicitly (tests use this).
func NewGeneratorWithTenants(configDir, tenantsDir string) *Generator {
	return &Generator{configDir: configDir, tenantsDir: tenantsDir}
}

// WriteConfig writes a Traefik dynamic configuration file for a tenant.
// The file routes {slug}.slate.local to the api-gateway, injecting X-Tenant-ID.
func (g *Generator) WriteConfig(tenantID, slug string) error {
	if err := os.MkdirAll(g.configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config dir: %w", err)
	}

	config := fmt.Sprintf(`http:
  routers:
    tenant-%s:
      rule: "Host(`+"`"+`%s.slate.local`+"`"+`)"
      entryPoints:
        - web
      service: api-gateway-svc
      middlewares:
        - inject-tenant-%s
  middlewares:
    inject-tenant-%s:
      headers:
        customRequestHeaders:
          X-Tenant-ID: "%s"
  services:
    api-gateway-svc:
      loadBalancer:
        servers:
          - url: "http://api-gateway:8080"
`, tenantID, slug, tenantID, tenantID, tenantID)

	path := filepath.Join(g.configDir, fmt.Sprintf("tenant-%s.yml", tenantID))
	if err := os.WriteFile(path, []byte(config), 0644); err != nil {
		return fmt.Errorf("failed to write traefik config: %w", err)
	}

	if err := g.WriteTenantEndpoints(slug); err != nil {
		return fmt.Errorf("failed to write tenant endpoints: %w", err)
	}
	return nil
}

// WriteTenantEndpoints writes the per-tenant service endpoint table consumed
// by the api-gateway (plan W16.3). Hostnames match the container names the
// DockerProvisioner uses (`{service}-{slug}`).
func (g *Generator) WriteTenantEndpoints(slug string) error {
	if err := os.MkdirAll(g.tenantsDir, 0755); err != nil {
		return fmt.Errorf("create tenants dir: %w", err)
	}
	content := fmt.Sprintf(`# Auto-generated by tenant-service (W16.3). Do not edit by hand —
# admin edits will be overwritten on the next tenant reconciliation.
tenant_slug: %s
services:
  user-auth:  "http://user-auth-%s:50051"
  course:     "http://course-%s:50052"
  assignment: "http://assignment-%s:50053"
  content:    "http://content-%s:50054"
  video:      "http://video-%s:50055"
  discussion: "http://discussion-%s:50056"
  scheduling: "http://scheduling-%s:50063"
  ai:         "http://ai-%s:50064"
`, slug, slug, slug, slug, slug, slug, slug, slug, slug)

	path := filepath.Join(g.tenantsDir, fmt.Sprintf("%s.yaml", slug))
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("write endpoints yaml: %w", err)
	}
	return nil
}

// DeleteConfig removes both the Traefik dynamic config and the endpoints yaml.
func (g *Generator) DeleteConfig(tenantID string) error {
	path := filepath.Join(g.configDir, fmt.Sprintf("tenant-%s.yml", tenantID))
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to delete traefik config: %w", err)
	}
	return nil
}

// DeleteTenantEndpoints removes the per-slug endpoints yaml.
func (g *Generator) DeleteTenantEndpoints(slug string) error {
	path := filepath.Join(g.tenantsDir, fmt.Sprintf("%s.yaml", slug))
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to delete endpoints yaml: %w", err)
	}
	return nil
}
