[smtp]
enabled = true
host = smtppro.zoho.com:587
user = noorullah.shaik@slate.college
password = 1995@Noot
skip_verify = false
from_address = noorullah.shaik@slate.college
from_name = Slate LMS Alerts
ehlo_identity = slate.college
starttls_policy = MandatoryStartTLS

[emails]
welcome_email_on_sign_up = false
templates_pattern = emails/*.html, emails/*.txt
content_types = text/html

[alerting]
enabled = false

[unified_alerting]
enabled = true
# How often alert rules should be evaluated
execute_alerts = true
# Default evaluation interval for alert rules
evaluation_timeout = 30s
# Maximum number of attempts to deliver an alert notification
max_attempts = 3
# Minimum interval between two evaluations of the same alert rule
min_interval = 10s
