global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          service: 'api-gateway'

  - job_name: 'user-auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-auth-service:9090']
        labels:
          service: 'user-auth-service'

  - job_name: 'course-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['course-service:3001']
        labels:
          service: 'course-service'

  - job_name: 'assignment-grading-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['assignment-grading-service:9090']
        labels:
          service: 'assignment-grading-service'

  - job_name: 'content-management-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['content-management-service:9092']
        labels:
          service: 'content-management-service'

  - job_name: 'onboarding-service'
    metrics_path: /health
    static_configs:
      - targets: ['onboarding-service:9081']
        labels:
          service: 'onboarding-service'

  - job_name: 'tenant-service'
    static_configs:
      - targets: ['tenant-service:9090']

  - job_name: 'metrics-service'
    metrics_path: /health
    static_configs:
      - targets: ['metrics-service:8087']
        labels:
          service: 'metrics-service'

  - job_name: 'video-conferencing-service'
    static_configs:
      - targets: ['video-conferencing-service:9092']
