// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: admin_auth.proto

package adminauthpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_admin_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,3,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	User            *AdminUser             `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_admin_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *LoginResponse) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_admin_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_admin_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_admin_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Audience      string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_admin_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateTokenResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ValidateTokenResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *ValidateTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListAdminUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersRequest) Reset() {
	*x = ListAdminUsersRequest{}
	mi := &file_admin_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersRequest) ProtoMessage() {}

func (x *ListAdminUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersRequest.ProtoReflect.Descriptor instead.
func (*ListAdminUsersRequest) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ListAdminUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAdminUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAdminUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUser           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersResponse) Reset() {
	*x = ListAdminUsersResponse{}
	mi := &file_admin_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersResponse) ProtoMessage() {}

func (x *ListAdminUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersResponse.ProtoReflect.Descriptor instead.
func (*ListAdminUsersResponse) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ListAdminUsersResponse) GetUsers() []*AdminUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListAdminUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_admin_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RegisterRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *AdminUser             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_admin_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterResponse) GetUser() *AdminUser {
	if x != nil {
		return x.User
	}
	return nil
}

type ImpersonateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   string                 `protobuf:"bytes,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantSlug    string                 `protobuf:"bytes,3,opt,name=tenant_slug,json=tenantSlug,proto3" json:"tenant_slug,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,4,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpersonateRequest) Reset() {
	*x = ImpersonateRequest{}
	mi := &file_admin_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpersonateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonateRequest) ProtoMessage() {}

func (x *ImpersonateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonateRequest.ProtoReflect.Descriptor instead.
func (*ImpersonateRequest) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ImpersonateRequest) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *ImpersonateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ImpersonateRequest) GetTenantSlug() string {
	if x != nil {
		return x.TenantSlug
	}
	return ""
}

func (x *ImpersonateRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type ImpersonateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Token           string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RedirectUrl     string                 `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	ImpersonationId string                 `protobuf:"bytes,3,opt,name=impersonation_id,json=impersonationId,proto3" json:"impersonation_id,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,4,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImpersonateResponse) Reset() {
	*x = ImpersonateResponse{}
	mi := &file_admin_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpersonateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonateResponse) ProtoMessage() {}

func (x *ImpersonateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonateResponse.ProtoReflect.Descriptor instead.
func (*ImpersonateResponse) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ImpersonateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ImpersonateResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *ImpersonateResponse) GetImpersonationId() string {
	if x != nil {
		return x.ImpersonationId
	}
	return ""
}

func (x *ImpersonateResponse) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

type AdminUser struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName        string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Roles           []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	Disabled        bool                   `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_admin_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{12}
}

func (x *AdminUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUser) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *AdminUser) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AdminUser) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *AdminUser) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *AdminUser) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type ListAdminRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// default 50, max 200; 0 = server default
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// opaque cursor; empty = first page
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminRolesRequest) Reset() {
	*x = ListAdminRolesRequest{}
	mi := &file_admin_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminRolesRequest) ProtoMessage() {}

func (x *ListAdminRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminRolesRequest.ProtoReflect.Descriptor instead.
func (*ListAdminRolesRequest) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{13}
}

func (x *ListAdminRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminRolesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAdminRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*AdminRole           `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminRolesResponse) Reset() {
	*x = ListAdminRolesResponse{}
	mi := &file_admin_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminRolesResponse) ProtoMessage() {}

func (x *ListAdminRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminRolesResponse.ProtoReflect.Descriptor instead.
func (*ListAdminRolesResponse) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ListAdminRolesResponse) GetRoles() []*AdminRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListAdminRolesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAdminRolesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AdminRole struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Row key — matches AdminUser.roles[] entries (platform_roles.name).
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Human-readable label derived server-side (e.g. "Super Admin").
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Permission strings in "resource:verb" format, or ["*"] for wildcard.
	Permissions     []string `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	CreatedAtUnixMs int64    `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminRole) Reset() {
	*x = AdminRole{}
	mi := &file_admin_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRole) ProtoMessage() {}

func (x *AdminRole) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRole.ProtoReflect.Descriptor instead.
func (*AdminRole) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{15}
}

func (x *AdminRole) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminRole) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AdminRole) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type GetAuditLogRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId *string                `protobuf:"bytes,1,opt,name=admin_user_id,json=adminUserId,proto3,oneof" json:"admin_user_id,omitempty"` // platform_audit.actor_id
	ActionType  *string                `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3,oneof" json:"action_type,omitempty"`      // platform_audit.action (exact match)
	TargetId    *string                `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
	TargetType  *string                `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3,oneof" json:"target_type,omitempty"`
	FromUnixMs  *int64                 `protobuf:"varint,5,opt,name=from_unix_ms,json=fromUnixMs,proto3,oneof" json:"from_unix_ms,omitempty"` // inclusive
	ToUnixMs    *int64                 `protobuf:"varint,6,opt,name=to_unix_ms,json=toUnixMs,proto3,oneof" json:"to_unix_ms,omitempty"`       // exclusive
	// default 50, max 500
	Limit int32 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	// opaque cursor; empty = newest page
	Cursor        string `protobuf:"bytes,8,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogRequest) Reset() {
	*x = GetAuditLogRequest{}
	mi := &file_admin_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogRequest) ProtoMessage() {}

func (x *GetAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{16}
}

func (x *GetAuditLogRequest) GetAdminUserId() string {
	if x != nil && x.AdminUserId != nil {
		return *x.AdminUserId
	}
	return ""
}

func (x *GetAuditLogRequest) GetActionType() string {
	if x != nil && x.ActionType != nil {
		return *x.ActionType
	}
	return ""
}

func (x *GetAuditLogRequest) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *GetAuditLogRequest) GetTargetType() string {
	if x != nil && x.TargetType != nil {
		return *x.TargetType
	}
	return ""
}

func (x *GetAuditLogRequest) GetFromUnixMs() int64 {
	if x != nil && x.FromUnixMs != nil {
		return *x.FromUnixMs
	}
	return 0
}

func (x *GetAuditLogRequest) GetToUnixMs() int64 {
	if x != nil && x.ToUnixMs != nil {
		return *x.ToUnixMs
	}
	return 0
}

func (x *GetAuditLogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAuditLogRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogResponse) Reset() {
	*x = GetAuditLogResponse{}
	mi := &file_admin_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogResponse) ProtoMessage() {}

func (x *GetAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{17}
}

func (x *GetAuditLogResponse) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetAuditLogResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type AuditEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminUserId string                 `protobuf:"bytes,2,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"` // platform_audit.actor_id
	AdminEmail  string                 `protobuf:"bytes,3,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`      // joined from platform_admins.email
	ActionType  string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`      // platform_audit.action
	TargetType  string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId    *string                `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
	// "success" | "failure" — derived from action_type suffix
	Outcome string `protobuf:"bytes,7,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// populated from metadata->>'reason' when present
	Error            *string           `protobuf:"bytes,8,opt,name=error,proto3,oneof" json:"error,omitempty"`
	OccurredAtUnixMs int64             `protobuf:"varint,9,opt,name=occurred_at_unix_ms,json=occurredAtUnixMs,proto3" json:"occurred_at_unix_ms,omitempty"` // platform_audit.created_at
	Metadata         map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestId        string            `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_admin_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{18}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *AuditEvent) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *AuditEvent) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *AuditEvent) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AuditEvent) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *AuditEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *AuditEvent) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *AuditEvent) GetOccurredAtUnixMs() int64 {
	if x != nil {
		return x.OccurredAtUnixMs
	}
	return 0
}

func (x *AuditEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuditEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RefreshAdminTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAdminTokenRequest) Reset() {
	*x = RefreshAdminTokenRequest{}
	mi := &file_admin_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAdminTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAdminTokenRequest) ProtoMessage() {}

func (x *RefreshAdminTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAdminTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshAdminTokenRequest) Descriptor() ([]byte, []int) {
	return file_admin_auth_proto_rawDescGZIP(), []int{19}
}

func (x *RefreshAdminTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_admin_auth_proto protoreflect.FileDescriptor

const file_admin_auth_proto_rawDesc = "" +
	"\n" +
	"\x10admin_auth.proto\x12\n" +
	"admin_auth\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xaf\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12+\n" +
	"\x12expires_at_unix_ms\x18\x03 \x01(\x03R\x0fexpiresAtUnixMs\x12)\n" +
	"\x04user\x18\x04 \x01(\v2\x15.admin_auth.AdminUserR\x04user\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xa4\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"E\n" +
	"\x15ListAdminUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"[\n" +
	"\x16ListAdminUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.admin_auth.AdminUserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x95\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\"=\n" +
	"\x10RegisterResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.admin_auth.AdminUserR\x04user\"\x9c\x01\n" +
	"\x12ImpersonateRequest\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\tR\vadminUserId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_slug\x18\x03 \x01(\tR\n" +
	"tenantSlug\x12$\n" +
	"\x0etarget_user_id\x18\x04 \x01(\tR\ftargetUserId\"\xa6\x01\n" +
	"\x13ImpersonateResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\fredirect_url\x18\x02 \x01(\tR\vredirectUrl\x12)\n" +
	"\x10impersonation_id\x18\x03 \x01(\tR\x0fimpersonationId\x12+\n" +
	"\x12expires_at_unix_ms\x18\x04 \x01(\x03R\x0fexpiresAtUnixMs\"\xda\x01\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12+\n" +
	"\x12created_at_unix_ms\x18\x05 \x01(\x03R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\x06 \x01(\x03R\x0fupdatedAtUnixMs\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\bR\bdisabled\"S\n" +
	"\x15ListAdminRolesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x16ListAdminRolesResponse\x12+\n" +
	"\x05roles\x18\x01 \x03(\v2\x15.admin_auth.AdminRoleR\x05roles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"\xa2\x01\n" +
	"\tAdminRole\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12+\n" +
	"\x12created_at_unix_ms\x18\x05 \x01(\x03R\x0fcreatedAtUnixMs\"\x83\x03\n" +
	"\x12GetAuditLogRequest\x12'\n" +
	"\radmin_user_id\x18\x01 \x01(\tH\x00R\vadminUserId\x88\x01\x01\x12$\n" +
	"\vaction_type\x18\x02 \x01(\tH\x01R\n" +
	"actionType\x88\x01\x01\x12 \n" +
	"\ttarget_id\x18\x03 \x01(\tH\x02R\btargetId\x88\x01\x01\x12$\n" +
	"\vtarget_type\x18\x04 \x01(\tH\x03R\n" +
	"targetType\x88\x01\x01\x12%\n" +
	"\ffrom_unix_ms\x18\x05 \x01(\x03H\x04R\n" +
	"fromUnixMs\x88\x01\x01\x12!\n" +
	"\n" +
	"to_unix_ms\x18\x06 \x01(\x03H\x05R\btoUnixMs\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\b \x01(\tR\x06cursorB\x10\n" +
	"\x0e_admin_user_idB\x0e\n" +
	"\f_action_typeB\f\n" +
	"\n" +
	"_target_idB\x0e\n" +
	"\f_target_typeB\x0f\n" +
	"\r_from_unix_msB\r\n" +
	"\v_to_unix_ms\"f\n" +
	"\x13GetAuditLogResponse\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.admin_auth.AuditEventR\x06events\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xdf\x03\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\radmin_user_id\x18\x02 \x01(\tR\vadminUserId\x12\x1f\n" +
	"\vadmin_email\x18\x03 \x01(\tR\n" +
	"adminEmail\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12 \n" +
	"\ttarget_id\x18\x06 \x01(\tH\x00R\btargetId\x88\x01\x01\x12\x18\n" +
	"\aoutcome\x18\a \x01(\tR\aoutcome\x12\x19\n" +
	"\x05error\x18\b \x01(\tH\x01R\x05error\x88\x01\x01\x12-\n" +
	"\x13occurred_at_unix_ms\x18\t \x01(\x03R\x10occurredAtUnixMs\x12@\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2$.admin_auth.AuditEvent.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\tR\trequestId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_target_idB\b\n" +
	"\x06_error\"0\n" +
	"\x18RefreshAdminTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xc4\x06\n" +
	"\x10AdminAuthService\x12A\n" +
	"\n" +
	"AdminLogin\x12\x18.admin_auth.LoginRequest\x1a\x19.admin_auth.LoginResponse\x12D\n" +
	"\vAdminLogout\x12\x19.admin_auth.LogoutRequest\x1a\x1a.admin_auth.LogoutResponse\x12Y\n" +
	"\x12ValidateAdminToken\x12 .admin_auth.ValidateTokenRequest\x1a!.admin_auth.ValidateTokenResponse\x12W\n" +
	"\x0eListAdminUsers\x12!.admin_auth.ListAdminUsersRequest\x1a\".admin_auth.ListAdminUsersResponse\x12E\n" +
	"\bRegister\x12\x1b.admin_auth.RegisterRequest\x1a\x1c.admin_auth.RegisterResponse\x12N\n" +
	"\vImpersonate\x12\x1e.admin_auth.ImpersonateRequest\x1a\x1f.admin_auth.ImpersonateResponse\x12]\n" +
	"\x1aGenerateImpersonationToken\x12\x1e.admin_auth.ImpersonateRequest\x1a\x1f.admin_auth.ImpersonateResponse\x12W\n" +
	"\x0eListAdminRoles\x12!.admin_auth.ListAdminRolesRequest\x1a\".admin_auth.ListAdminRolesResponse\x12N\n" +
	"\vGetAuditLog\x12\x1e.admin_auth.GetAuditLogRequest\x1a\x1f.admin_auth.GetAuditLogResponse\x12T\n" +
	"\x11RefreshAdminToken\x12$.admin_auth.RefreshAdminTokenRequest\x1a\x19.admin_auth.LoginResponseB9Z7slate/services/admin-auth-service/api/proto/adminauthpbb\x06proto3"

var (
	file_admin_auth_proto_rawDescOnce sync.Once
	file_admin_auth_proto_rawDescData []byte
)

func file_admin_auth_proto_rawDescGZIP() []byte {
	file_admin_auth_proto_rawDescOnce.Do(func() {
		file_admin_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_auth_proto_rawDesc), len(file_admin_auth_proto_rawDesc)))
	})
	return file_admin_auth_proto_rawDescData
}

var file_admin_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_admin_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),             // 0: admin_auth.LoginRequest
	(*LoginResponse)(nil),            // 1: admin_auth.LoginResponse
	(*LogoutRequest)(nil),            // 2: admin_auth.LogoutRequest
	(*LogoutResponse)(nil),           // 3: admin_auth.LogoutResponse
	(*ValidateTokenRequest)(nil),     // 4: admin_auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),    // 5: admin_auth.ValidateTokenResponse
	(*ListAdminUsersRequest)(nil),    // 6: admin_auth.ListAdminUsersRequest
	(*ListAdminUsersResponse)(nil),   // 7: admin_auth.ListAdminUsersResponse
	(*RegisterRequest)(nil),          // 8: admin_auth.RegisterRequest
	(*RegisterResponse)(nil),         // 9: admin_auth.RegisterResponse
	(*ImpersonateRequest)(nil),       // 10: admin_auth.ImpersonateRequest
	(*ImpersonateResponse)(nil),      // 11: admin_auth.ImpersonateResponse
	(*AdminUser)(nil),                // 12: admin_auth.AdminUser
	(*ListAdminRolesRequest)(nil),    // 13: admin_auth.ListAdminRolesRequest
	(*ListAdminRolesResponse)(nil),   // 14: admin_auth.ListAdminRolesResponse
	(*AdminRole)(nil),                // 15: admin_auth.AdminRole
	(*GetAuditLogRequest)(nil),       // 16: admin_auth.GetAuditLogRequest
	(*GetAuditLogResponse)(nil),      // 17: admin_auth.GetAuditLogResponse
	(*AuditEvent)(nil),               // 18: admin_auth.AuditEvent
	(*RefreshAdminTokenRequest)(nil), // 19: admin_auth.RefreshAdminTokenRequest
	nil,                              // 20: admin_auth.AuditEvent.MetadataEntry
}
var file_admin_auth_proto_depIdxs = []int32{
	12, // 0: admin_auth.LoginResponse.user:type_name -> admin_auth.AdminUser
	12, // 1: admin_auth.ListAdminUsersResponse.users:type_name -> admin_auth.AdminUser
	12, // 2: admin_auth.RegisterResponse.user:type_name -> admin_auth.AdminUser
	15, // 3: admin_auth.ListAdminRolesResponse.roles:type_name -> admin_auth.AdminRole
	18, // 4: admin_auth.GetAuditLogResponse.events:type_name -> admin_auth.AuditEvent
	20, // 5: admin_auth.AuditEvent.metadata:type_name -> admin_auth.AuditEvent.MetadataEntry
	0,  // 6: admin_auth.AdminAuthService.AdminLogin:input_type -> admin_auth.LoginRequest
	2,  // 7: admin_auth.AdminAuthService.AdminLogout:input_type -> admin_auth.LogoutRequest
	4,  // 8: admin_auth.AdminAuthService.ValidateAdminToken:input_type -> admin_auth.ValidateTokenRequest
	6,  // 9: admin_auth.AdminAuthService.ListAdminUsers:input_type -> admin_auth.ListAdminUsersRequest
	8,  // 10: admin_auth.AdminAuthService.Register:input_type -> admin_auth.RegisterRequest
	10, // 11: admin_auth.AdminAuthService.Impersonate:input_type -> admin_auth.ImpersonateRequest
	10, // 12: admin_auth.AdminAuthService.GenerateImpersonationToken:input_type -> admin_auth.ImpersonateRequest
	13, // 13: admin_auth.AdminAuthService.ListAdminRoles:input_type -> admin_auth.ListAdminRolesRequest
	16, // 14: admin_auth.AdminAuthService.GetAuditLog:input_type -> admin_auth.GetAuditLogRequest
	19, // 15: admin_auth.AdminAuthService.RefreshAdminToken:input_type -> admin_auth.RefreshAdminTokenRequest
	1,  // 16: admin_auth.AdminAuthService.AdminLogin:output_type -> admin_auth.LoginResponse
	3,  // 17: admin_auth.AdminAuthService.AdminLogout:output_type -> admin_auth.LogoutResponse
	5,  // 18: admin_auth.AdminAuthService.ValidateAdminToken:output_type -> admin_auth.ValidateTokenResponse
	7,  // 19: admin_auth.AdminAuthService.ListAdminUsers:output_type -> admin_auth.ListAdminUsersResponse
	9,  // 20: admin_auth.AdminAuthService.Register:output_type -> admin_auth.RegisterResponse
	11, // 21: admin_auth.AdminAuthService.Impersonate:output_type -> admin_auth.ImpersonateResponse
	11, // 22: admin_auth.AdminAuthService.GenerateImpersonationToken:output_type -> admin_auth.ImpersonateResponse
	14, // 23: admin_auth.AdminAuthService.ListAdminRoles:output_type -> admin_auth.ListAdminRolesResponse
	17, // 24: admin_auth.AdminAuthService.GetAuditLog:output_type -> admin_auth.GetAuditLogResponse
	1,  // 25: admin_auth.AdminAuthService.RefreshAdminToken:output_type -> admin_auth.LoginResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_admin_auth_proto_init() }
func file_admin_auth_proto_init() {
	if File_admin_auth_proto != nil {
		return
	}
	file_admin_auth_proto_msgTypes[16].OneofWrappers = []any{}
	file_admin_auth_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_auth_proto_rawDesc), len(file_admin_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_auth_proto_goTypes,
		DependencyIndexes: file_admin_auth_proto_depIdxs,
		MessageInfos:      file_admin_auth_proto_msgTypes,
	}.Build()
	File_admin_auth_proto = out.File
	file_admin_auth_proto_goTypes = nil
	file_admin_auth_proto_depIdxs = nil
}
