// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: admin_auth.proto

package adminauthpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminAuthService_AdminLogin_FullMethodName                 = "/admin_auth.AdminAuthService/AdminLogin"
	AdminAuthService_AdminLogout_FullMethodName                = "/admin_auth.AdminAuthService/AdminLogout"
	AdminAuthService_ValidateAdminToken_FullMethodName         = "/admin_auth.AdminAuthService/ValidateAdminToken"
	AdminAuthService_ListAdminUsers_FullMethodName             = "/admin_auth.AdminAuthService/ListAdminUsers"
	AdminAuthService_Register_FullMethodName                   = "/admin_auth.AdminAuthService/Register"
	AdminAuthService_Impersonate_FullMethodName                = "/admin_auth.AdminAuthService/Impersonate"
	AdminAuthService_GenerateImpersonationToken_FullMethodName = "/admin_auth.AdminAuthService/GenerateImpersonationToken"
	AdminAuthService_ListAdminRoles_FullMethodName             = "/admin_auth.AdminAuthService/ListAdminRoles"
	AdminAuthService_GetAuditLog_FullMethodName                = "/admin_auth.AdminAuthService/GetAuditLog"
	AdminAuthService_RefreshAdminToken_FullMethodName          = "/admin_auth.AdminAuthService/RefreshAdminToken"
)

// AdminAuthServiceClient is the client API for AdminAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminAuthService is the platform-level auth plane for Slate administrators.
// Contract ratified in plan/CONTRACTS.md (W2).
type AdminAuthServiceClient interface {
	// AdminLogin authenticates a platform admin and returns a JWT with aud=platform.
	AdminLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// AdminLogout revokes an active admin token (Redis blacklist).
	AdminLogout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// ValidateAdminToken verifies a JWT and checks aud=platform.
	ValidateAdminToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	// ListAdminUsers returns all platform admins (admin-fe /iam/users).
	ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error)
	// Register creates a new platform admin.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Impersonate issues a short-lived RSA-signed impersonation token + redirect URL.
	Impersonate(ctx context.Context, in *ImpersonateRequest, opts ...grpc.CallOption) (*ImpersonateResponse, error)
	// GenerateImpersonationToken is an alias of Impersonate kept for plan W2.2 naming.
	GenerateImpersonationToken(ctx context.Context, in *ImpersonateRequest, opts ...grpc.CallOption) (*ImpersonateResponse, error)
	// ListAdminRoles returns all platform roles with their permissions (W2.5).
	// Reads platform_roles. Powers admin-fe /iam/roles.
	ListAdminRoles(ctx context.Context, in *ListAdminRolesRequest, opts ...grpc.CallOption) (*ListAdminRolesResponse, error)
	// GetAuditLog returns paginated platform_audit rows filtered by actor/action/time (W2.5).
	// Powers admin-fe /iam/audit.
	GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*GetAuditLogResponse, error)
	// RefreshAdminToken exchanges a refresh token for a new access+refresh pair (W2.5).
	// Rotates the refresh token (old jti revoked).
	RefreshAdminToken(ctx context.Context, in *RefreshAdminTokenRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type adminAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminAuthServiceClient(cc grpc.ClientConnInterface) AdminAuthServiceClient {
	return &adminAuthServiceClient{cc}
}

func (c *adminAuthServiceClient) AdminLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_AdminLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAuthServiceClient) AdminLogout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_AdminLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAuthServiceClient) ValidateAdminToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_ValidateAdminToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAuthServiceClient) ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUsersResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_ListAdminUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAuthServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAuthServiceClient) Impersonate(ctx context.Context, in *ImpersonateRequest, opts ...grpc.CallOption) (*ImpersonateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImpersonateResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_Impersonate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAuthServiceClient) GenerateImpersonationToken(ctx context.Context, in *ImpersonateRequest, opts ...grpc.CallOption) (*ImpersonateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImpersonateResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_GenerateImpersonationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAuthServiceClient) ListAdminRoles(ctx context.Context, in *ListAdminRolesRequest, opts ...grpc.CallOption) (*ListAdminRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminRolesResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_ListAdminRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAuthServiceClient) GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*GetAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_GetAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminAuthServiceClient) RefreshAdminToken(ctx context.Context, in *RefreshAdminTokenRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AdminAuthService_RefreshAdminToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminAuthServiceServer is the server API for AdminAuthService service.
// All implementations must embed UnimplementedAdminAuthServiceServer
// for forward compatibility.
//
// AdminAuthService is the platform-level auth plane for Slate administrators.
// Contract ratified in plan/CONTRACTS.md (W2).
type AdminAuthServiceServer interface {
	// AdminLogin authenticates a platform admin and returns a JWT with aud=platform.
	AdminLogin(context.Context, *LoginRequest) (*LoginResponse, error)
	// AdminLogout revokes an active admin token (Redis blacklist).
	AdminLogout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// ValidateAdminToken verifies a JWT and checks aud=platform.
	ValidateAdminToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// ListAdminUsers returns all platform admins (admin-fe /iam/users).
	ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error)
	// Register creates a new platform admin.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Impersonate issues a short-lived RSA-signed impersonation token + redirect URL.
	Impersonate(context.Context, *ImpersonateRequest) (*ImpersonateResponse, error)
	// GenerateImpersonationToken is an alias of Impersonate kept for plan W2.2 naming.
	GenerateImpersonationToken(context.Context, *ImpersonateRequest) (*ImpersonateResponse, error)
	// ListAdminRoles returns all platform roles with their permissions (W2.5).
	// Reads platform_roles. Powers admin-fe /iam/roles.
	ListAdminRoles(context.Context, *ListAdminRolesRequest) (*ListAdminRolesResponse, error)
	// GetAuditLog returns paginated platform_audit rows filtered by actor/action/time (W2.5).
	// Powers admin-fe /iam/audit.
	GetAuditLog(context.Context, *GetAuditLogRequest) (*GetAuditLogResponse, error)
	// RefreshAdminToken exchanges a refresh token for a new access+refresh pair (W2.5).
	// Rotates the refresh token (old jti revoked).
	RefreshAdminToken(context.Context, *RefreshAdminTokenRequest) (*LoginResponse, error)
	mustEmbedUnimplementedAdminAuthServiceServer()
}

// UnimplementedAdminAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminAuthServiceServer struct{}

func (UnimplementedAdminAuthServiceServer) AdminLogin(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminLogin not implemented")
}
func (UnimplementedAdminAuthServiceServer) AdminLogout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminLogout not implemented")
}
func (UnimplementedAdminAuthServiceServer) ValidateAdminToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAdminToken not implemented")
}
func (UnimplementedAdminAuthServiceServer) ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminUsers not implemented")
}
func (UnimplementedAdminAuthServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAdminAuthServiceServer) Impersonate(context.Context, *ImpersonateRequest) (*ImpersonateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Impersonate not implemented")
}
func (UnimplementedAdminAuthServiceServer) GenerateImpersonationToken(context.Context, *ImpersonateRequest) (*ImpersonateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateImpersonationToken not implemented")
}
func (UnimplementedAdminAuthServiceServer) ListAdminRoles(context.Context, *ListAdminRolesRequest) (*ListAdminRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminRoles not implemented")
}
func (UnimplementedAdminAuthServiceServer) GetAuditLog(context.Context, *GetAuditLogRequest) (*GetAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditLog not implemented")
}
func (UnimplementedAdminAuthServiceServer) RefreshAdminToken(context.Context, *RefreshAdminTokenRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshAdminToken not implemented")
}
func (UnimplementedAdminAuthServiceServer) mustEmbedUnimplementedAdminAuthServiceServer() {}
func (UnimplementedAdminAuthServiceServer) testEmbeddedByValue()                          {}

// UnsafeAdminAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminAuthServiceServer will
// result in compilation errors.
type UnsafeAdminAuthServiceServer interface {
	mustEmbedUnimplementedAdminAuthServiceServer()
}

func RegisterAdminAuthServiceServer(s grpc.ServiceRegistrar, srv AdminAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminAuthService_ServiceDesc, srv)
}

func _AdminAuthService_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_AdminLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).AdminLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAuthService_AdminLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).AdminLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_AdminLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).AdminLogout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAuthService_ValidateAdminToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).ValidateAdminToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_ValidateAdminToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).ValidateAdminToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAuthService_ListAdminUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).ListAdminUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_ListAdminUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).ListAdminUsers(ctx, req.(*ListAdminUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAuthService_Impersonate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImpersonateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).Impersonate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_Impersonate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).Impersonate(ctx, req.(*ImpersonateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAuthService_GenerateImpersonationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImpersonateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).GenerateImpersonationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_GenerateImpersonationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).GenerateImpersonationToken(ctx, req.(*ImpersonateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAuthService_ListAdminRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).ListAdminRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_ListAdminRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).ListAdminRoles(ctx, req.(*ListAdminRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAuthService_GetAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).GetAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_GetAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).GetAuditLog(ctx, req.(*GetAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminAuthService_RefreshAdminToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAdminTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAuthServiceServer).RefreshAdminToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminAuthService_RefreshAdminToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAuthServiceServer).RefreshAdminToken(ctx, req.(*RefreshAdminTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminAuthService_ServiceDesc is the grpc.ServiceDesc for AdminAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_auth.AdminAuthService",
	HandlerType: (*AdminAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminLogin",
			Handler:    _AdminAuthService_AdminLogin_Handler,
		},
		{
			MethodName: "AdminLogout",
			Handler:    _AdminAuthService_AdminLogout_Handler,
		},
		{
			MethodName: "ValidateAdminToken",
			Handler:    _AdminAuthService_ValidateAdminToken_Handler,
		},
		{
			MethodName: "ListAdminUsers",
			Handler:    _AdminAuthService_ListAdminUsers_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AdminAuthService_Register_Handler,
		},
		{
			MethodName: "Impersonate",
			Handler:    _AdminAuthService_Impersonate_Handler,
		},
		{
			MethodName: "GenerateImpersonationToken",
			Handler:    _AdminAuthService_GenerateImpersonationToken_Handler,
		},
		{
			MethodName: "ListAdminRoles",
			Handler:    _AdminAuthService_ListAdminRoles_Handler,
		},
		{
			MethodName: "GetAuditLog",
			Handler:    _AdminAuthService_GetAuditLog_Handler,
		},
		{
			MethodName: "RefreshAdminToken",
			Handler:    _AdminAuthService_RefreshAdminToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_auth.proto",
}
