// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: incident.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IncidentService_CreateIncident_FullMethodName    = "/incident.IncidentService/CreateIncident"
	IncidentService_UpdateIncident_FullMethodName    = "/incident.IncidentService/UpdateIncident"
	IncidentService_ListIncidents_FullMethodName     = "/incident.IncidentService/ListIncidents"
	IncidentService_GetIncident_FullMethodName       = "/incident.IncidentService/GetIncident"
	IncidentService_PostIncidentEvent_FullMethodName = "/incident.IncidentService/PostIncidentEvent"
	IncidentService_GetPublicStatus_FullMethodName   = "/incident.IncidentService/GetPublicStatus"
)

// IncidentServiceClient is the client API for IncidentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IncidentService is the platform-level service that tracks operational
// incidents and exposes a public status page.
//
// Ratified contract: plan/CONTRACTS.md#incident.IncidentService (W4)
type IncidentServiceClient interface {
	CreateIncident(ctx context.Context, in *CreateIncidentRequest, opts ...grpc.CallOption) (*Incident, error)
	UpdateIncident(ctx context.Context, in *UpdateIncidentRequest, opts ...grpc.CallOption) (*Incident, error)
	ListIncidents(ctx context.Context, in *ListIncidentsRequest, opts ...grpc.CallOption) (*ListIncidentsResponse, error)
	GetIncident(ctx context.Context, in *GetIncidentRequest, opts ...grpc.CallOption) (*Incident, error)
	PostIncidentEvent(ctx context.Context, in *PostIncidentEventRequest, opts ...grpc.CallOption) (*IncidentEvent, error)
	GetPublicStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PublicStatusResponse, error)
}

type incidentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIncidentServiceClient(cc grpc.ClientConnInterface) IncidentServiceClient {
	return &incidentServiceClient{cc}
}

func (c *incidentServiceClient) CreateIncident(ctx context.Context, in *CreateIncidentRequest, opts ...grpc.CallOption) (*Incident, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Incident)
	err := c.cc.Invoke(ctx, IncidentService_CreateIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incidentServiceClient) UpdateIncident(ctx context.Context, in *UpdateIncidentRequest, opts ...grpc.CallOption) (*Incident, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Incident)
	err := c.cc.Invoke(ctx, IncidentService_UpdateIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incidentServiceClient) ListIncidents(ctx context.Context, in *ListIncidentsRequest, opts ...grpc.CallOption) (*ListIncidentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIncidentsResponse)
	err := c.cc.Invoke(ctx, IncidentService_ListIncidents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incidentServiceClient) GetIncident(ctx context.Context, in *GetIncidentRequest, opts ...grpc.CallOption) (*Incident, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Incident)
	err := c.cc.Invoke(ctx, IncidentService_GetIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incidentServiceClient) PostIncidentEvent(ctx context.Context, in *PostIncidentEventRequest, opts ...grpc.CallOption) (*IncidentEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncidentEvent)
	err := c.cc.Invoke(ctx, IncidentService_PostIncidentEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incidentServiceClient) GetPublicStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PublicStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicStatusResponse)
	err := c.cc.Invoke(ctx, IncidentService_GetPublicStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncidentServiceServer is the server API for IncidentService service.
// All implementations must embed UnimplementedIncidentServiceServer
// for forward compatibility.
//
// IncidentService is the platform-level service that tracks operational
// incidents and exposes a public status page.
//
// Ratified contract: plan/CONTRACTS.md#incident.IncidentService (W4)
type IncidentServiceServer interface {
	CreateIncident(context.Context, *CreateIncidentRequest) (*Incident, error)
	UpdateIncident(context.Context, *UpdateIncidentRequest) (*Incident, error)
	ListIncidents(context.Context, *ListIncidentsRequest) (*ListIncidentsResponse, error)
	GetIncident(context.Context, *GetIncidentRequest) (*Incident, error)
	PostIncidentEvent(context.Context, *PostIncidentEventRequest) (*IncidentEvent, error)
	GetPublicStatus(context.Context, *emptypb.Empty) (*PublicStatusResponse, error)
	mustEmbedUnimplementedIncidentServiceServer()
}

// UnimplementedIncidentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIncidentServiceServer struct{}

func (UnimplementedIncidentServiceServer) CreateIncident(context.Context, *CreateIncidentRequest) (*Incident, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIncident not implemented")
}
func (UnimplementedIncidentServiceServer) UpdateIncident(context.Context, *UpdateIncidentRequest) (*Incident, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateIncident not implemented")
}
func (UnimplementedIncidentServiceServer) ListIncidents(context.Context, *ListIncidentsRequest) (*ListIncidentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIncidents not implemented")
}
func (UnimplementedIncidentServiceServer) GetIncident(context.Context, *GetIncidentRequest) (*Incident, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIncident not implemented")
}
func (UnimplementedIncidentServiceServer) PostIncidentEvent(context.Context, *PostIncidentEventRequest) (*IncidentEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method PostIncidentEvent not implemented")
}
func (UnimplementedIncidentServiceServer) GetPublicStatus(context.Context, *emptypb.Empty) (*PublicStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicStatus not implemented")
}
func (UnimplementedIncidentServiceServer) mustEmbedUnimplementedIncidentServiceServer() {}
func (UnimplementedIncidentServiceServer) testEmbeddedByValue()                         {}

// UnsafeIncidentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncidentServiceServer will
// result in compilation errors.
type UnsafeIncidentServiceServer interface {
	mustEmbedUnimplementedIncidentServiceServer()
}

func RegisterIncidentServiceServer(s grpc.ServiceRegistrar, srv IncidentServiceServer) {
	// If the following call panics, it indicates UnimplementedIncidentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IncidentService_ServiceDesc, srv)
}

func _IncidentService_CreateIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentServiceServer).CreateIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncidentService_CreateIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentServiceServer).CreateIncident(ctx, req.(*CreateIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncidentService_UpdateIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentServiceServer).UpdateIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncidentService_UpdateIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentServiceServer).UpdateIncident(ctx, req.(*UpdateIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncidentService_ListIncidents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIncidentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentServiceServer).ListIncidents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncidentService_ListIncidents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentServiceServer).ListIncidents(ctx, req.(*ListIncidentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncidentService_GetIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentServiceServer).GetIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncidentService_GetIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentServiceServer).GetIncident(ctx, req.(*GetIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncidentService_PostIncidentEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostIncidentEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentServiceServer).PostIncidentEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncidentService_PostIncidentEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentServiceServer).PostIncidentEvent(ctx, req.(*PostIncidentEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncidentService_GetPublicStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentServiceServer).GetPublicStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncidentService_GetPublicStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentServiceServer).GetPublicStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IncidentService_ServiceDesc is the grpc.ServiceDesc for IncidentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IncidentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "incident.IncidentService",
	HandlerType: (*IncidentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIncident",
			Handler:    _IncidentService_CreateIncident_Handler,
		},
		{
			MethodName: "UpdateIncident",
			Handler:    _IncidentService_UpdateIncident_Handler,
		},
		{
			MethodName: "ListIncidents",
			Handler:    _IncidentService_ListIncidents_Handler,
		},
		{
			MethodName: "GetIncident",
			Handler:    _IncidentService_GetIncident_Handler,
		},
		{
			MethodName: "PostIncidentEvent",
			Handler:    _IncidentService_PostIncidentEvent_Handler,
		},
		{
			MethodName: "GetPublicStatus",
			Handler:    _IncidentService_GetPublicStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "incident.proto",
}
