// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: incident.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_P0                   Priority = 1
	Priority_P1                   Priority = 2
	Priority_P2                   Priority = 3
	Priority_P3                   Priority = 4
	Priority_P4                   Priority = 5
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "P0",
		2: "P1",
		3: "P2",
		4: "P3",
		5: "P4",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"P0":                   1,
		"P1":                   2,
		"P2":                   3,
		"P3":                   4,
		"P4":                   5,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_incident_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_incident_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{0}
}

type IncidentStatus int32

const (
	IncidentStatus_INCIDENT_STATUS_UNSPECIFIED IncidentStatus = 0
	IncidentStatus_OPEN                        IncidentStatus = 1
	IncidentStatus_WATCHING                    IncidentStatus = 2
	IncidentStatus_RESOLVED                    IncidentStatus = 3
)

// Enum value maps for IncidentStatus.
var (
	IncidentStatus_name = map[int32]string{
		0: "INCIDENT_STATUS_UNSPECIFIED",
		1: "OPEN",
		2: "WATCHING",
		3: "RESOLVED",
	}
	IncidentStatus_value = map[string]int32{
		"INCIDENT_STATUS_UNSPECIFIED": 0,
		"OPEN":                        1,
		"WATCHING":                    2,
		"RESOLVED":                    3,
	}
)

func (x IncidentStatus) Enum() *IncidentStatus {
	p := new(IncidentStatus)
	*p = x
	return p
}

func (x IncidentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_incident_proto_enumTypes[1].Descriptor()
}

func (IncidentStatus) Type() protoreflect.EnumType {
	return &file_incident_proto_enumTypes[1]
}

func (x IncidentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentStatus.Descriptor instead.
func (IncidentStatus) EnumDescriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{1}
}

type StatusFilter int32

const (
	StatusFilter_STATUS_FILTER_UNSPECIFIED StatusFilter = 0
	StatusFilter_FILTER_OPEN               StatusFilter = 1
	StatusFilter_FILTER_WATCH              StatusFilter = 2
	StatusFilter_FILTER_RESOLVED           StatusFilter = 3
)

// Enum value maps for StatusFilter.
var (
	StatusFilter_name = map[int32]string{
		0: "STATUS_FILTER_UNSPECIFIED",
		1: "FILTER_OPEN",
		2: "FILTER_WATCH",
		3: "FILTER_RESOLVED",
	}
	StatusFilter_value = map[string]int32{
		"STATUS_FILTER_UNSPECIFIED": 0,
		"FILTER_OPEN":               1,
		"FILTER_WATCH":              2,
		"FILTER_RESOLVED":           3,
	}
)

func (x StatusFilter) Enum() *StatusFilter {
	p := new(StatusFilter)
	*p = x
	return p
}

func (x StatusFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_incident_proto_enumTypes[2].Descriptor()
}

func (StatusFilter) Type() protoreflect.EnumType {
	return &file_incident_proto_enumTypes[2]
}

func (x StatusFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusFilter.Descriptor instead.
func (StatusFilter) EnumDescriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{2}
}

type OverallStatus int32

const (
	OverallStatus_OVERALL_STATUS_UNSPECIFIED OverallStatus = 0
	OverallStatus_OPERATIONAL                OverallStatus = 1
	OverallStatus_DEGRADED                   OverallStatus = 2
	OverallStatus_OUTAGE                     OverallStatus = 3
)

// Enum value maps for OverallStatus.
var (
	OverallStatus_name = map[int32]string{
		0: "OVERALL_STATUS_UNSPECIFIED",
		1: "OPERATIONAL",
		2: "DEGRADED",
		3: "OUTAGE",
	}
	OverallStatus_value = map[string]int32{
		"OVERALL_STATUS_UNSPECIFIED": 0,
		"OPERATIONAL":                1,
		"DEGRADED":                   2,
		"OUTAGE":                     3,
	}
)

func (x OverallStatus) Enum() *OverallStatus {
	p := new(OverallStatus)
	*p = x
	return p
}

func (x OverallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_incident_proto_enumTypes[3].Descriptor()
}

func (OverallStatus) Type() protoreflect.EnumType {
	return &file_incident_proto_enumTypes[3]
}

func (x OverallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverallStatus.Descriptor instead.
func (OverallStatus) EnumDescriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{3}
}

type ComponentHealth int32

const (
	ComponentHealth_COMPONENT_HEALTH_UNSPECIFIED ComponentHealth = 0
	ComponentHealth_GREEN                        ComponentHealth = 1
	ComponentHealth_AMBER                        ComponentHealth = 2
	ComponentHealth_RED                          ComponentHealth = 3
)

// Enum value maps for ComponentHealth.
var (
	ComponentHealth_name = map[int32]string{
		0: "COMPONENT_HEALTH_UNSPECIFIED",
		1: "GREEN",
		2: "AMBER",
		3: "RED",
	}
	ComponentHealth_value = map[string]int32{
		"COMPONENT_HEALTH_UNSPECIFIED": 0,
		"GREEN":                        1,
		"AMBER":                        2,
		"RED":                          3,
	}
)

func (x ComponentHealth) Enum() *ComponentHealth {
	p := new(ComponentHealth)
	*p = x
	return p
}

func (x ComponentHealth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentHealth) Descriptor() protoreflect.EnumDescriptor {
	return file_incident_proto_enumTypes[4].Descriptor()
}

func (ComponentHealth) Type() protoreflect.EnumType {
	return &file_incident_proto_enumTypes[4]
}

func (x ComponentHealth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentHealth.Descriptor instead.
func (ComponentHealth) EnumDescriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{4}
}

type Incident struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         *string                `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	Priority         Priority               `protobuf:"varint,3,opt,name=priority,proto3,enum=incident.Priority" json:"priority,omitempty"`
	Status           IncidentStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=incident.IncidentStatus" json:"status,omitempty"`
	Title            string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Impact           string                 `protobuf:"bytes,6,opt,name=impact,proto3" json:"impact,omitempty"`
	OpenedAtUnixMs   int64                  `protobuf:"varint,7,opt,name=opened_at_unix_ms,json=openedAtUnixMs,proto3" json:"opened_at_unix_ms,omitempty"`
	ResolvedAtUnixMs *int64                 `protobuf:"varint,8,opt,name=resolved_at_unix_ms,json=resolvedAtUnixMs,proto3,oneof" json:"resolved_at_unix_ms,omitempty"`
	Events           []*IncidentEvent       `protobuf:"bytes,9,rep,name=events,proto3" json:"events,omitempty"`
	Service          *string                `protobuf:"bytes,10,opt,name=service,proto3,oneof" json:"service,omitempty"`
	CreatedBy        *string                `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{0}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *Incident) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *Incident) GetStatus() IncidentStatus {
	if x != nil {
		return x.Status
	}
	return IncidentStatus_INCIDENT_STATUS_UNSPECIFIED
}

func (x *Incident) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Incident) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *Incident) GetOpenedAtUnixMs() int64 {
	if x != nil {
		return x.OpenedAtUnixMs
	}
	return 0
}

func (x *Incident) GetResolvedAtUnixMs() int64 {
	if x != nil && x.ResolvedAtUnixMs != nil {
		return *x.ResolvedAtUnixMs
	}
	return 0
}

func (x *Incident) GetEvents() []*IncidentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Incident) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *Incident) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

type IncidentEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncidentId      string                 `protobuf:"bytes,2,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	ActorId         *string                `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3,oneof" json:"actor_id,omitempty"`
	EventType       string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Content         string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IncidentEvent) Reset() {
	*x = IncidentEvent{}
	mi := &file_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentEvent) ProtoMessage() {}

func (x *IncidentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentEvent.ProtoReflect.Descriptor instead.
func (*IncidentEvent) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{1}
}

func (x *IncidentEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IncidentEvent) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *IncidentEvent) GetActorId() string {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return ""
}

func (x *IncidentEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *IncidentEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IncidentEvent) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type CreateIncidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *string                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	Priority      Priority               `protobuf:"varint,2,opt,name=priority,proto3,enum=incident.Priority" json:"priority,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Impact        string                 `protobuf:"bytes,4,opt,name=impact,proto3" json:"impact,omitempty"`
	Service       *string                `protobuf:"bytes,5,opt,name=service,proto3,oneof" json:"service,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIncidentRequest) Reset() {
	*x = CreateIncidentRequest{}
	mi := &file_incident_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncidentRequest) ProtoMessage() {}

func (x *CreateIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncidentRequest.ProtoReflect.Descriptor instead.
func (*CreateIncidentRequest) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIncidentRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *CreateIncidentRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *CreateIncidentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateIncidentRequest) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

func (x *CreateIncidentRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

func (x *CreateIncidentRequest) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

type UpdateIncidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        *IncidentStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=incident.IncidentStatus,oneof" json:"status,omitempty"`
	Priority      *Priority              `protobuf:"varint,3,opt,name=priority,proto3,enum=incident.Priority,oneof" json:"priority,omitempty"`
	Title         *string                `protobuf:"bytes,4,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Impact        *string                `protobuf:"bytes,5,opt,name=impact,proto3,oneof" json:"impact,omitempty"`
	ActorId       *string                `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3,oneof" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentRequest) Reset() {
	*x = UpdateIncidentRequest{}
	mi := &file_incident_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentRequest) ProtoMessage() {}

func (x *UpdateIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentRequest.ProtoReflect.Descriptor instead.
func (*UpdateIncidentRequest) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateIncidentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIncidentRequest) GetStatus() IncidentStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return IncidentStatus_INCIDENT_STATUS_UNSPECIFIED
}

func (x *UpdateIncidentRequest) GetPriority() Priority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *UpdateIncidentRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateIncidentRequest) GetImpact() string {
	if x != nil && x.Impact != nil {
		return *x.Impact
	}
	return ""
}

func (x *UpdateIncidentRequest) GetActorId() string {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return ""
}

type ListIncidentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *string                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	StatusFilter  *StatusFilter          `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=incident.StatusFilter,oneof" json:"status_filter,omitempty"`
	Priority      *Priority              `protobuf:"varint,3,opt,name=priority,proto3,enum=incident.Priority,oneof" json:"priority,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentsRequest) Reset() {
	*x = ListIncidentsRequest{}
	mi := &file_incident_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentsRequest) ProtoMessage() {}

func (x *ListIncidentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentsRequest.ProtoReflect.Descriptor instead.
func (*ListIncidentsRequest) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{4}
}

func (x *ListIncidentsRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ListIncidentsRequest) GetStatusFilter() StatusFilter {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return StatusFilter_STATUS_FILTER_UNSPECIFIED
}

func (x *ListIncidentsRequest) GetPriority() Priority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *ListIncidentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListIncidentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incidents     []*Incident            `protobuf:"bytes,1,rep,name=incidents,proto3" json:"incidents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentsResponse) Reset() {
	*x = ListIncidentsResponse{}
	mi := &file_incident_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentsResponse) ProtoMessage() {}

func (x *ListIncidentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentsResponse.ProtoReflect.Descriptor instead.
func (*ListIncidentsResponse) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{5}
}

func (x *ListIncidentsResponse) GetIncidents() []*Incident {
	if x != nil {
		return x.Incidents
	}
	return nil
}

type GetIncidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentRequest) Reset() {
	*x = GetIncidentRequest{}
	mi := &file_incident_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentRequest) ProtoMessage() {}

func (x *GetIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentRequest.ProtoReflect.Descriptor instead.
func (*GetIncidentRequest) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{6}
}

func (x *GetIncidentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PostIncidentEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	ActorId       *string                `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3,oneof" json:"actor_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostIncidentEventRequest) Reset() {
	*x = PostIncidentEventRequest{}
	mi := &file_incident_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostIncidentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostIncidentEventRequest) ProtoMessage() {}

func (x *PostIncidentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostIncidentEventRequest.ProtoReflect.Descriptor instead.
func (*PostIncidentEventRequest) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{7}
}

func (x *PostIncidentEventRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *PostIncidentEventRequest) GetActorId() string {
	if x != nil && x.ActorId != nil {
		return *x.ActorId
	}
	return ""
}

func (x *PostIncidentEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PostIncidentEventRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ComponentStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Service         string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Health          ComponentHealth        `protobuf:"varint,2,opt,name=health,proto3,enum=incident.ComponentHealth" json:"health,omitempty"`
	OpenIncidents   int32                  `protobuf:"varint,3,opt,name=open_incidents,json=openIncidents,proto3" json:"open_incidents,omitempty"`
	HighestPriority *Priority              `protobuf:"varint,4,opt,name=highest_priority,json=highestPriority,proto3,enum=incident.Priority,oneof" json:"highest_priority,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComponentStatus) Reset() {
	*x = ComponentStatus{}
	mi := &file_incident_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStatus) ProtoMessage() {}

func (x *ComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStatus.ProtoReflect.Descriptor instead.
func (*ComponentStatus) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{8}
}

func (x *ComponentStatus) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ComponentStatus) GetHealth() ComponentHealth {
	if x != nil {
		return x.Health
	}
	return ComponentHealth_COMPONENT_HEALTH_UNSPECIFIED
}

func (x *ComponentStatus) GetOpenIncidents() int32 {
	if x != nil {
		return x.OpenIncidents
	}
	return 0
}

func (x *ComponentStatus) GetHighestPriority() Priority {
	if x != nil && x.HighestPriority != nil {
		return *x.HighestPriority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

type PublicStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Overall           OverallStatus          `protobuf:"varint,1,opt,name=overall,proto3,enum=incident.OverallStatus" json:"overall,omitempty"`
	Components        []*ComponentStatus     `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	IncidentsLast_7D  int32                  `protobuf:"varint,3,opt,name=incidents_last_7d,json=incidentsLast7d,proto3" json:"incidents_last_7d,omitempty"`
	GeneratedAtUnixMs int64                  `protobuf:"varint,4,opt,name=generated_at_unix_ms,json=generatedAtUnixMs,proto3" json:"generated_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PublicStatusResponse) Reset() {
	*x = PublicStatusResponse{}
	mi := &file_incident_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicStatusResponse) ProtoMessage() {}

func (x *PublicStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incident_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicStatusResponse.ProtoReflect.Descriptor instead.
func (*PublicStatusResponse) Descriptor() ([]byte, []int) {
	return file_incident_proto_rawDescGZIP(), []int{9}
}

func (x *PublicStatusResponse) GetOverall() OverallStatus {
	if x != nil {
		return x.Overall
	}
	return OverallStatus_OVERALL_STATUS_UNSPECIFIED
}

func (x *PublicStatusResponse) GetComponents() []*ComponentStatus {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *PublicStatusResponse) GetIncidentsLast_7D() int32 {
	if x != nil {
		return x.IncidentsLast_7D
	}
	return 0
}

func (x *PublicStatusResponse) GetGeneratedAtUnixMs() int64 {
	if x != nil {
		return x.GeneratedAtUnixMs
	}
	return 0
}

var File_incident_proto protoreflect.FileDescriptor

const file_incident_proto_rawDesc = "" +
	"\n" +
	"\x0eincident.proto\x12\bincident\x1a\x1bgoogle/protobuf/empty.proto\"\xe0\x03\n" +
	"\bIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\tH\x00R\btenantId\x88\x01\x01\x12.\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x12.incident.PriorityR\bpriority\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.incident.IncidentStatusR\x06status\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x16\n" +
	"\x06impact\x18\x06 \x01(\tR\x06impact\x12)\n" +
	"\x11opened_at_unix_ms\x18\a \x01(\x03R\x0eopenedAtUnixMs\x122\n" +
	"\x13resolved_at_unix_ms\x18\b \x01(\x03H\x01R\x10resolvedAtUnixMs\x88\x01\x01\x12/\n" +
	"\x06events\x18\t \x03(\v2\x17.incident.IncidentEventR\x06events\x12\x1d\n" +
	"\aservice\x18\n" +
	" \x01(\tH\x02R\aservice\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\v \x01(\tH\x03R\tcreatedBy\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\x16\n" +
	"\x14_resolved_at_unix_msB\n" +
	"\n" +
	"\b_serviceB\r\n" +
	"\v_created_by\"\xd3\x01\n" +
	"\rIncidentEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vincident_id\x18\x02 \x01(\tR\n" +
	"incidentId\x12\x1e\n" +
	"\bactor_id\x18\x03 \x01(\tH\x00R\aactorId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12+\n" +
	"\x12created_at_unix_ms\x18\x06 \x01(\x03R\x0fcreatedAtUnixMsB\v\n" +
	"\t_actor_id\"\x83\x02\n" +
	"\x15CreateIncidentRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12.\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x12.incident.PriorityR\bpriority\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06impact\x18\x04 \x01(\tR\x06impact\x12\x1d\n" +
	"\aservice\x18\x05 \x01(\tH\x01R\aservice\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tH\x02R\tcreatedBy\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\n" +
	"\n" +
	"\b_serviceB\r\n" +
	"\v_created_by\"\xa5\x02\n" +
	"\x15UpdateIncidentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.incident.IncidentStatusH\x00R\x06status\x88\x01\x01\x123\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x12.incident.PriorityH\x01R\bpriority\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x04 \x01(\tH\x02R\x05title\x88\x01\x01\x12\x1b\n" +
	"\x06impact\x18\x05 \x01(\tH\x03R\x06impact\x88\x01\x01\x12\x1e\n" +
	"\bactor_id\x18\x06 \x01(\tH\x04R\aactorId\x88\x01\x01B\t\n" +
	"\a_statusB\v\n" +
	"\t_priorityB\b\n" +
	"\x06_titleB\t\n" +
	"\a_impactB\v\n" +
	"\t_actor_id\"\xf2\x01\n" +
	"\x14ListIncidentsRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12@\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x16.incident.StatusFilterH\x01R\fstatusFilter\x88\x01\x01\x123\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x12.incident.PriorityH\x02R\bpriority\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\f\n" +
	"\n" +
	"_tenant_idB\x10\n" +
	"\x0e_status_filterB\v\n" +
	"\t_priority\"I\n" +
	"\x15ListIncidentsResponse\x120\n" +
	"\tincidents\x18\x01 \x03(\v2\x12.incident.IncidentR\tincidents\"$\n" +
	"\x12GetIncidentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x01\n" +
	"\x18PostIncidentEventRequest\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x1e\n" +
	"\bactor_id\x18\x02 \x01(\tH\x00R\aactorId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontentB\v\n" +
	"\t_actor_id\"\xde\x01\n" +
	"\x0fComponentStatus\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x121\n" +
	"\x06health\x18\x02 \x01(\x0e2\x19.incident.ComponentHealthR\x06health\x12%\n" +
	"\x0eopen_incidents\x18\x03 \x01(\x05R\ropenIncidents\x12B\n" +
	"\x10highest_priority\x18\x04 \x01(\x0e2\x12.incident.PriorityH\x00R\x0fhighestPriority\x88\x01\x01B\x13\n" +
	"\x11_highest_priority\"\xe1\x01\n" +
	"\x14PublicStatusResponse\x121\n" +
	"\aoverall\x18\x01 \x01(\x0e2\x17.incident.OverallStatusR\aoverall\x129\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x19.incident.ComponentStatusR\n" +
	"components\x12*\n" +
	"\x11incidents_last_7d\x18\x03 \x01(\x05R\x0fincidentsLast7d\x12/\n" +
	"\x14generated_at_unix_ms\x18\x04 \x01(\x03R\x11generatedAtUnixMs*L\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02P0\x10\x01\x12\x06\n" +
	"\x02P1\x10\x02\x12\x06\n" +
	"\x02P2\x10\x03\x12\x06\n" +
	"\x02P3\x10\x04\x12\x06\n" +
	"\x02P4\x10\x05*W\n" +
	"\x0eIncidentStatus\x12\x1f\n" +
	"\x1bINCIDENT_STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\f\n" +
	"\bWATCHING\x10\x02\x12\f\n" +
	"\bRESOLVED\x10\x03*e\n" +
	"\fStatusFilter\x12\x1d\n" +
	"\x19STATUS_FILTER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vFILTER_OPEN\x10\x01\x12\x10\n" +
	"\fFILTER_WATCH\x10\x02\x12\x13\n" +
	"\x0fFILTER_RESOLVED\x10\x03*Z\n" +
	"\rOverallStatus\x12\x1e\n" +
	"\x1aOVERALL_STATUS_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOPERATIONAL\x10\x01\x12\f\n" +
	"\bDEGRADED\x10\x02\x12\n" +
	"\n" +
	"\x06OUTAGE\x10\x03*R\n" +
	"\x0fComponentHealth\x12 \n" +
	"\x1cCOMPONENT_HEALTH_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05GREEN\x10\x01\x12\t\n" +
	"\x05AMBER\x10\x02\x12\a\n" +
	"\x03RED\x10\x032\xcf\x03\n" +
	"\x0fIncidentService\x12E\n" +
	"\x0eCreateIncident\x12\x1f.incident.CreateIncidentRequest\x1a\x12.incident.Incident\x12E\n" +
	"\x0eUpdateIncident\x12\x1f.incident.UpdateIncidentRequest\x1a\x12.incident.Incident\x12P\n" +
	"\rListIncidents\x12\x1e.incident.ListIncidentsRequest\x1a\x1f.incident.ListIncidentsResponse\x12?\n" +
	"\vGetIncident\x12\x1c.incident.GetIncidentRequest\x1a\x12.incident.Incident\x12P\n" +
	"\x11PostIncidentEvent\x12\".incident.PostIncidentEventRequest\x1a\x17.incident.IncidentEvent\x12I\n" +
	"\x0fGetPublicStatus\x12\x16.google.protobuf.Empty\x1a\x1e.incident.PublicStatusResponseB+Z)slate/services/incident-service/api/protob\x06proto3"

var (
	file_incident_proto_rawDescOnce sync.Once
	file_incident_proto_rawDescData []byte
)

func file_incident_proto_rawDescGZIP() []byte {
	file_incident_proto_rawDescOnce.Do(func() {
		file_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incident_proto_rawDesc), len(file_incident_proto_rawDesc)))
	})
	return file_incident_proto_rawDescData
}

var file_incident_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_incident_proto_goTypes = []any{
	(Priority)(0),                    // 0: incident.Priority
	(IncidentStatus)(0),              // 1: incident.IncidentStatus
	(StatusFilter)(0),                // 2: incident.StatusFilter
	(OverallStatus)(0),               // 3: incident.OverallStatus
	(ComponentHealth)(0),             // 4: incident.ComponentHealth
	(*Incident)(nil),                 // 5: incident.Incident
	(*IncidentEvent)(nil),            // 6: incident.IncidentEvent
	(*CreateIncidentRequest)(nil),    // 7: incident.CreateIncidentRequest
	(*UpdateIncidentRequest)(nil),    // 8: incident.UpdateIncidentRequest
	(*ListIncidentsRequest)(nil),     // 9: incident.ListIncidentsRequest
	(*ListIncidentsResponse)(nil),    // 10: incident.ListIncidentsResponse
	(*GetIncidentRequest)(nil),       // 11: incident.GetIncidentRequest
	(*PostIncidentEventRequest)(nil), // 12: incident.PostIncidentEventRequest
	(*ComponentStatus)(nil),          // 13: incident.ComponentStatus
	(*PublicStatusResponse)(nil),     // 14: incident.PublicStatusResponse
	(*emptypb.Empty)(nil),            // 15: google.protobuf.Empty
}
var file_incident_proto_depIdxs = []int32{
	0,  // 0: incident.Incident.priority:type_name -> incident.Priority
	1,  // 1: incident.Incident.status:type_name -> incident.IncidentStatus
	6,  // 2: incident.Incident.events:type_name -> incident.IncidentEvent
	0,  // 3: incident.CreateIncidentRequest.priority:type_name -> incident.Priority
	1,  // 4: incident.UpdateIncidentRequest.status:type_name -> incident.IncidentStatus
	0,  // 5: incident.UpdateIncidentRequest.priority:type_name -> incident.Priority
	2,  // 6: incident.ListIncidentsRequest.status_filter:type_name -> incident.StatusFilter
	0,  // 7: incident.ListIncidentsRequest.priority:type_name -> incident.Priority
	5,  // 8: incident.ListIncidentsResponse.incidents:type_name -> incident.Incident
	4,  // 9: incident.ComponentStatus.health:type_name -> incident.ComponentHealth
	0,  // 10: incident.ComponentStatus.highest_priority:type_name -> incident.Priority
	3,  // 11: incident.PublicStatusResponse.overall:type_name -> incident.OverallStatus
	13, // 12: incident.PublicStatusResponse.components:type_name -> incident.ComponentStatus
	7,  // 13: incident.IncidentService.CreateIncident:input_type -> incident.CreateIncidentRequest
	8,  // 14: incident.IncidentService.UpdateIncident:input_type -> incident.UpdateIncidentRequest
	9,  // 15: incident.IncidentService.ListIncidents:input_type -> incident.ListIncidentsRequest
	11, // 16: incident.IncidentService.GetIncident:input_type -> incident.GetIncidentRequest
	12, // 17: incident.IncidentService.PostIncidentEvent:input_type -> incident.PostIncidentEventRequest
	15, // 18: incident.IncidentService.GetPublicStatus:input_type -> google.protobuf.Empty
	5,  // 19: incident.IncidentService.CreateIncident:output_type -> incident.Incident
	5,  // 20: incident.IncidentService.UpdateIncident:output_type -> incident.Incident
	10, // 21: incident.IncidentService.ListIncidents:output_type -> incident.ListIncidentsResponse
	5,  // 22: incident.IncidentService.GetIncident:output_type -> incident.Incident
	6,  // 23: incident.IncidentService.PostIncidentEvent:output_type -> incident.IncidentEvent
	14, // 24: incident.IncidentService.GetPublicStatus:output_type -> incident.PublicStatusResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_incident_proto_init() }
func file_incident_proto_init() {
	if File_incident_proto != nil {
		return
	}
	file_incident_proto_msgTypes[0].OneofWrappers = []any{}
	file_incident_proto_msgTypes[1].OneofWrappers = []any{}
	file_incident_proto_msgTypes[2].OneofWrappers = []any{}
	file_incident_proto_msgTypes[3].OneofWrappers = []any{}
	file_incident_proto_msgTypes[4].OneofWrappers = []any{}
	file_incident_proto_msgTypes[7].OneofWrappers = []any{}
	file_incident_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incident_proto_rawDesc), len(file_incident_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_incident_proto_goTypes,
		DependencyIndexes: file_incident_proto_depIdxs,
		EnumInfos:         file_incident_proto_enumTypes,
		MessageInfos:      file_incident_proto_msgTypes,
	}.Build()
	File_incident_proto = out.File
	file_incident_proto_goTypes = nil
	file_incident_proto_depIdxs = nil
}
