// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsService_GetSystemMetrics_FullMethodName           = "/metrics.MetricsService/GetSystemMetrics"
	MetricsService_GetTenantMetrics_FullMethodName           = "/metrics.MetricsService/GetTenantMetrics"
	MetricsService_ListTenantMetrics_FullMethodName          = "/metrics.MetricsService/ListTenantMetrics"
	MetricsService_GetRealtimeMetrics_FullMethodName         = "/metrics.MetricsService/GetRealtimeMetrics"
	MetricsService_StreamRealtimeMetrics_FullMethodName      = "/metrics.MetricsService/StreamRealtimeMetrics"
	MetricsService_GetActiveAlerts_FullMethodName            = "/metrics.MetricsService/GetActiveAlerts"
	MetricsService_GetAlertHistory_FullMethodName            = "/metrics.MetricsService/GetAlertHistory"
	MetricsService_RecordAPIRequest_FullMethodName           = "/metrics.MetricsService/RecordAPIRequest"
	MetricsService_RecordError_FullMethodName                = "/metrics.MetricsService/RecordError"
	MetricsService_GetPlatformMetrics_FullMethodName         = "/metrics.MetricsService/GetPlatformMetrics"
	MetricsService_GetStudentProgress_FullMethodName         = "/metrics.MetricsService/GetStudentProgress"
	MetricsService_GetGradeDistribution_FullMethodName       = "/metrics.MetricsService/GetGradeDistribution"
	MetricsService_GetStudentComparison_FullMethodName       = "/metrics.MetricsService/GetStudentComparison"
	MetricsService_GetRosterHealth_FullMethodName            = "/metrics.MetricsService/GetRosterHealth"
	MetricsService_CreateExport_FullMethodName               = "/metrics.MetricsService/CreateExport"
	MetricsService_GetExport_FullMethodName                  = "/metrics.MetricsService/GetExport"
	MetricsService_GetPlatformMetricsExtended_FullMethodName = "/metrics.MetricsService/GetPlatformMetricsExtended"
)

// MetricsServiceClient is the client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Metrics service for SaaS admin usage metrics dashboard (US-9.2)
// and student analytics (grade distribution, progress tracking)
type MetricsServiceClient interface {
	// System-wide metrics (AC1, AC2, AC3, AC4)
	GetSystemMetrics(ctx context.Context, in *GetSystemMetricsRequest, opts ...grpc.CallOption) (*SystemMetricsResponse, error)
	// Tenant-level breakdown (AC5)
	GetTenantMetrics(ctx context.Context, in *GetTenantMetricsRequest, opts ...grpc.CallOption) (*TenantMetricsResponse, error)
	ListTenantMetrics(ctx context.Context, in *ListTenantMetricsRequest, opts ...grpc.CallOption) (*ListTenantMetricsResponse, error)
	// Real-time metrics (AC3, AC6)
	GetRealtimeMetrics(ctx context.Context, in *GetRealtimeMetricsRequest, opts ...grpc.CallOption) (*RealtimeMetricsResponse, error)
	StreamRealtimeMetrics(ctx context.Context, in *StreamRealtimeMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RealtimeMetricsResponse], error)
	// Alerts (AC7)
	GetActiveAlerts(ctx context.Context, in *GetActiveAlertsRequest, opts ...grpc.CallOption) (*AlertsResponse, error)
	GetAlertHistory(ctx context.Context, in *GetAlertHistoryRequest, opts ...grpc.CallOption) (*AlertHistoryResponse, error)
	// Record usage (internal)
	RecordAPIRequest(ctx context.Context, in *RecordAPIRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RecordError(ctx context.Context, in *RecordErrorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Platform metrics (admin dashboard)
	GetPlatformMetrics(ctx context.Context, in *PlatformMetricsRequest, opts ...grpc.CallOption) (*PlatformMetricsResponse, error)
	// Student progress analytics
	GetStudentProgress(ctx context.Context, in *StudentProgressRequest, opts ...grpc.CallOption) (*StudentProgressResponse, error)
	// Grade distribution for a course
	GetGradeDistribution(ctx context.Context, in *GradeDistributionRequest, opts ...grpc.CallOption) (*GradeDistributionResponse, error)
	// Student comparison against class
	GetStudentComparison(ctx context.Context, in *StudentComparisonRequest, opts ...grpc.CallOption) (*StudentComparisonResponse, error)
	// W12.1 roster health — students classified healthy/slipping/at_risk.
	// Additive per PO ratification (plan/CONTRACTS.md metrics.MetricsService W12).
	GetRosterHealth(ctx context.Context, in *GetRosterHealthRequest, opts ...grpc.CallOption) (*GetRosterHealthResponse, error)
	// W12.3 export reports — create async export job.
	// Additive per PO ratification.
	CreateExport(ctx context.Context, in *CreateExportRequest, opts ...grpc.CallOption) (*ExportJob, error)
	// W12.3 export reports — poll job status.
	GetExport(ctx context.Context, in *GetExportRequest, opts ...grpc.CallOption) (*ExportJob, error)
	// W12.4 extended platform stats — adds tenant MAU, 30d signups,
	// uptime, active incident count. Sibling of GetPlatformMetrics.
	GetPlatformMetricsExtended(ctx context.Context, in *PlatformMetricsRequest, opts ...grpc.CallOption) (*PlatformMetricsExtendedResponse, error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) GetSystemMetrics(ctx context.Context, in *GetSystemMetricsRequest, opts ...grpc.CallOption) (*SystemMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemMetricsResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetSystemMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetTenantMetrics(ctx context.Context, in *GetTenantMetricsRequest, opts ...grpc.CallOption) (*TenantMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantMetricsResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetTenantMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) ListTenantMetrics(ctx context.Context, in *ListTenantMetricsRequest, opts ...grpc.CallOption) (*ListTenantMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantMetricsResponse)
	err := c.cc.Invoke(ctx, MetricsService_ListTenantMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetRealtimeMetrics(ctx context.Context, in *GetRealtimeMetricsRequest, opts ...grpc.CallOption) (*RealtimeMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RealtimeMetricsResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetRealtimeMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) StreamRealtimeMetrics(ctx context.Context, in *StreamRealtimeMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RealtimeMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[0], MetricsService_StreamRealtimeMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRealtimeMetricsRequest, RealtimeMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamRealtimeMetricsClient = grpc.ServerStreamingClient[RealtimeMetricsResponse]

func (c *metricsServiceClient) GetActiveAlerts(ctx context.Context, in *GetActiveAlertsRequest, opts ...grpc.CallOption) (*AlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertsResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetActiveAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetAlertHistory(ctx context.Context, in *GetAlertHistoryRequest, opts ...grpc.CallOption) (*AlertHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertHistoryResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetAlertHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) RecordAPIRequest(ctx context.Context, in *RecordAPIRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetricsService_RecordAPIRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) RecordError(ctx context.Context, in *RecordErrorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetricsService_RecordError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetPlatformMetrics(ctx context.Context, in *PlatformMetricsRequest, opts ...grpc.CallOption) (*PlatformMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformMetricsResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetPlatformMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetStudentProgress(ctx context.Context, in *StudentProgressRequest, opts ...grpc.CallOption) (*StudentProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentProgressResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetStudentProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetGradeDistribution(ctx context.Context, in *GradeDistributionRequest, opts ...grpc.CallOption) (*GradeDistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeDistributionResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetGradeDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetStudentComparison(ctx context.Context, in *StudentComparisonRequest, opts ...grpc.CallOption) (*StudentComparisonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentComparisonResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetStudentComparison_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetRosterHealth(ctx context.Context, in *GetRosterHealthRequest, opts ...grpc.CallOption) (*GetRosterHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRosterHealthResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetRosterHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) CreateExport(ctx context.Context, in *CreateExportRequest, opts ...grpc.CallOption) (*ExportJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportJob)
	err := c.cc.Invoke(ctx, MetricsService_CreateExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetExport(ctx context.Context, in *GetExportRequest, opts ...grpc.CallOption) (*ExportJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportJob)
	err := c.cc.Invoke(ctx, MetricsService_GetExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) GetPlatformMetricsExtended(ctx context.Context, in *PlatformMetricsRequest, opts ...grpc.CallOption) (*PlatformMetricsExtendedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlatformMetricsExtendedResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetPlatformMetricsExtended_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServiceServer is the server API for MetricsService service.
// All implementations must embed UnimplementedMetricsServiceServer
// for forward compatibility.
//
// Metrics service for SaaS admin usage metrics dashboard (US-9.2)
// and student analytics (grade distribution, progress tracking)
type MetricsServiceServer interface {
	// System-wide metrics (AC1, AC2, AC3, AC4)
	GetSystemMetrics(context.Context, *GetSystemMetricsRequest) (*SystemMetricsResponse, error)
	// Tenant-level breakdown (AC5)
	GetTenantMetrics(context.Context, *GetTenantMetricsRequest) (*TenantMetricsResponse, error)
	ListTenantMetrics(context.Context, *ListTenantMetricsRequest) (*ListTenantMetricsResponse, error)
	// Real-time metrics (AC3, AC6)
	GetRealtimeMetrics(context.Context, *GetRealtimeMetricsRequest) (*RealtimeMetricsResponse, error)
	StreamRealtimeMetrics(*StreamRealtimeMetricsRequest, grpc.ServerStreamingServer[RealtimeMetricsResponse]) error
	// Alerts (AC7)
	GetActiveAlerts(context.Context, *GetActiveAlertsRequest) (*AlertsResponse, error)
	GetAlertHistory(context.Context, *GetAlertHistoryRequest) (*AlertHistoryResponse, error)
	// Record usage (internal)
	RecordAPIRequest(context.Context, *RecordAPIRequestRequest) (*emptypb.Empty, error)
	RecordError(context.Context, *RecordErrorRequest) (*emptypb.Empty, error)
	// Platform metrics (admin dashboard)
	GetPlatformMetrics(context.Context, *PlatformMetricsRequest) (*PlatformMetricsResponse, error)
	// Student progress analytics
	GetStudentProgress(context.Context, *StudentProgressRequest) (*StudentProgressResponse, error)
	// Grade distribution for a course
	GetGradeDistribution(context.Context, *GradeDistributionRequest) (*GradeDistributionResponse, error)
	// Student comparison against class
	GetStudentComparison(context.Context, *StudentComparisonRequest) (*StudentComparisonResponse, error)
	// W12.1 roster health — students classified healthy/slipping/at_risk.
	// Additive per PO ratification (plan/CONTRACTS.md metrics.MetricsService W12).
	GetRosterHealth(context.Context, *GetRosterHealthRequest) (*GetRosterHealthResponse, error)
	// W12.3 export reports — create async export job.
	// Additive per PO ratification.
	CreateExport(context.Context, *CreateExportRequest) (*ExportJob, error)
	// W12.3 export reports — poll job status.
	GetExport(context.Context, *GetExportRequest) (*ExportJob, error)
	// W12.4 extended platform stats — adds tenant MAU, 30d signups,
	// uptime, active incident count. Sibling of GetPlatformMetrics.
	GetPlatformMetricsExtended(context.Context, *PlatformMetricsRequest) (*PlatformMetricsExtendedResponse, error)
	mustEmbedUnimplementedMetricsServiceServer()
}

// UnimplementedMetricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServiceServer struct{}

func (UnimplementedMetricsServiceServer) GetSystemMetrics(context.Context, *GetSystemMetricsRequest) (*SystemMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) GetTenantMetrics(context.Context, *GetTenantMetricsRequest) (*TenantMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) ListTenantMetrics(context.Context, *ListTenantMetricsRequest) (*ListTenantMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenantMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) GetRealtimeMetrics(context.Context, *GetRealtimeMetricsRequest) (*RealtimeMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRealtimeMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) StreamRealtimeMetrics(*StreamRealtimeMetricsRequest, grpc.ServerStreamingServer[RealtimeMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamRealtimeMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) GetActiveAlerts(context.Context, *GetActiveAlertsRequest) (*AlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveAlerts not implemented")
}
func (UnimplementedMetricsServiceServer) GetAlertHistory(context.Context, *GetAlertHistoryRequest) (*AlertHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlertHistory not implemented")
}
func (UnimplementedMetricsServiceServer) RecordAPIRequest(context.Context, *RecordAPIRequestRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordAPIRequest not implemented")
}
func (UnimplementedMetricsServiceServer) RecordError(context.Context, *RecordErrorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordError not implemented")
}
func (UnimplementedMetricsServiceServer) GetPlatformMetrics(context.Context, *PlatformMetricsRequest) (*PlatformMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) GetStudentProgress(context.Context, *StudentProgressRequest) (*StudentProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentProgress not implemented")
}
func (UnimplementedMetricsServiceServer) GetGradeDistribution(context.Context, *GradeDistributionRequest) (*GradeDistributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGradeDistribution not implemented")
}
func (UnimplementedMetricsServiceServer) GetStudentComparison(context.Context, *StudentComparisonRequest) (*StudentComparisonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStudentComparison not implemented")
}
func (UnimplementedMetricsServiceServer) GetRosterHealth(context.Context, *GetRosterHealthRequest) (*GetRosterHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRosterHealth not implemented")
}
func (UnimplementedMetricsServiceServer) CreateExport(context.Context, *CreateExportRequest) (*ExportJob, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExport not implemented")
}
func (UnimplementedMetricsServiceServer) GetExport(context.Context, *GetExportRequest) (*ExportJob, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExport not implemented")
}
func (UnimplementedMetricsServiceServer) GetPlatformMetricsExtended(context.Context, *PlatformMetricsRequest) (*PlatformMetricsExtendedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatformMetricsExtended not implemented")
}
func (UnimplementedMetricsServiceServer) mustEmbedUnimplementedMetricsServiceServer() {}
func (UnimplementedMetricsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServiceServer will
// result in compilation errors.
type UnsafeMetricsServiceServer interface {
	mustEmbedUnimplementedMetricsServiceServer()
}

func RegisterMetricsServiceServer(s grpc.ServiceRegistrar, srv MetricsServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsService_ServiceDesc, srv)
}

func _MetricsService_GetSystemMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetSystemMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetSystemMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetSystemMetrics(ctx, req.(*GetSystemMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetTenantMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetTenantMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetTenantMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetTenantMetrics(ctx, req.(*GetTenantMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_ListTenantMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).ListTenantMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_ListTenantMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).ListTenantMetrics(ctx, req.(*ListTenantMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetRealtimeMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRealtimeMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetRealtimeMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetRealtimeMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetRealtimeMetrics(ctx, req.(*GetRealtimeMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_StreamRealtimeMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRealtimeMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetricsServiceServer).StreamRealtimeMetrics(m, &grpc.GenericServerStream[StreamRealtimeMetricsRequest, RealtimeMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamRealtimeMetricsServer = grpc.ServerStreamingServer[RealtimeMetricsResponse]

func _MetricsService_GetActiveAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetActiveAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetActiveAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetActiveAlerts(ctx, req.(*GetActiveAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetAlertHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetAlertHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetAlertHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetAlertHistory(ctx, req.(*GetAlertHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_RecordAPIRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAPIRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).RecordAPIRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_RecordAPIRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).RecordAPIRequest(ctx, req.(*RecordAPIRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_RecordError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).RecordError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_RecordError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).RecordError(ctx, req.(*RecordErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetPlatformMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetPlatformMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetPlatformMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetPlatformMetrics(ctx, req.(*PlatformMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetStudentProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetStudentProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetStudentProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetStudentProgress(ctx, req.(*StudentProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetGradeDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetGradeDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetGradeDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetGradeDistribution(ctx, req.(*GradeDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetStudentComparison_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentComparisonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetStudentComparison(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetStudentComparison_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetStudentComparison(ctx, req.(*StudentComparisonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetRosterHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRosterHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetRosterHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetRosterHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetRosterHealth(ctx, req.(*GetRosterHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_CreateExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).CreateExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_CreateExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).CreateExport(ctx, req.(*CreateExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetExport(ctx, req.(*GetExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_GetPlatformMetricsExtended_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatformMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetPlatformMetricsExtended(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetPlatformMetricsExtended_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetPlatformMetricsExtended(ctx, req.(*PlatformMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsService_ServiceDesc is the grpc.ServiceDesc for MetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemMetrics",
			Handler:    _MetricsService_GetSystemMetrics_Handler,
		},
		{
			MethodName: "GetTenantMetrics",
			Handler:    _MetricsService_GetTenantMetrics_Handler,
		},
		{
			MethodName: "ListTenantMetrics",
			Handler:    _MetricsService_ListTenantMetrics_Handler,
		},
		{
			MethodName: "GetRealtimeMetrics",
			Handler:    _MetricsService_GetRealtimeMetrics_Handler,
		},
		{
			MethodName: "GetActiveAlerts",
			Handler:    _MetricsService_GetActiveAlerts_Handler,
		},
		{
			MethodName: "GetAlertHistory",
			Handler:    _MetricsService_GetAlertHistory_Handler,
		},
		{
			MethodName: "RecordAPIRequest",
			Handler:    _MetricsService_RecordAPIRequest_Handler,
		},
		{
			MethodName: "RecordError",
			Handler:    _MetricsService_RecordError_Handler,
		},
		{
			MethodName: "GetPlatformMetrics",
			Handler:    _MetricsService_GetPlatformMetrics_Handler,
		},
		{
			MethodName: "GetStudentProgress",
			Handler:    _MetricsService_GetStudentProgress_Handler,
		},
		{
			MethodName: "GetGradeDistribution",
			Handler:    _MetricsService_GetGradeDistribution_Handler,
		},
		{
			MethodName: "GetStudentComparison",
			Handler:    _MetricsService_GetStudentComparison_Handler,
		},
		{
			MethodName: "GetRosterHealth",
			Handler:    _MetricsService_GetRosterHealth_Handler,
		},
		{
			MethodName: "CreateExport",
			Handler:    _MetricsService_CreateExport_Handler,
		},
		{
			MethodName: "GetExport",
			Handler:    _MetricsService_GetExport_Handler,
		},
		{
			MethodName: "GetPlatformMetricsExtended",
			Handler:    _MetricsService_GetPlatformMetricsExtended_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRealtimeMetrics",
			Handler:       _MetricsService_StreamRealtimeMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "metrics.proto",
}
